// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: rpc/proto/executor.proto

package executor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_rpc_proto_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Notice        *ResponseNotice        `protobuf:"bytes,2,opt,name=notice,proto3" json:"notice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_rpc_proto_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingResponse) GetNotice() *ResponseNotice {
	if x != nil {
		return x.Notice
	}
	return nil
}

type ResponseNotice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Hint          string                 `protobuf:"bytes,4,opt,name=hint,proto3" json:"hint,omitempty"`
	Stage         string                 `protobuf:"bytes,5,opt,name=stage,proto3" json:"stage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseNotice) Reset() {
	*x = ResponseNotice{}
	mi := &file_rpc_proto_executor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseNotice) ProtoMessage() {}

func (x *ResponseNotice) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_executor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseNotice.ProtoReflect.Descriptor instead.
func (*ResponseNotice) Descriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseNotice) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResponseNotice) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseNotice) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseNotice) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

func (x *ResponseNotice) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

type CreateOrderRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChainId           int64                  `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	SettlementAddress string                 `protobuf:"bytes,2,opt,name=settlementAddress,proto3" json:"settlementAddress,omitempty"`
	OrderHash         string                 `protobuf:"bytes,3,opt,name=orderHash,proto3" json:"orderHash,omitempty"`
	Maker             string                 `protobuf:"bytes,4,opt,name=maker,proto3" json:"maker,omitempty"`
	InputToken        string                 `protobuf:"bytes,5,opt,name=inputToken,proto3" json:"inputToken,omitempty"`
	OutputToken       string                 `protobuf:"bytes,6,opt,name=outputToken,proto3" json:"outputToken,omitempty"`
	AmountIn          string                 `protobuf:"bytes,7,opt,name=amountIn,proto3" json:"amountIn,omitempty"`
	MinAmountOut      string                 `protobuf:"bytes,8,opt,name=minAmountOut,proto3" json:"minAmountOut,omitempty"`
	TriggerPriceX18   string                 `protobuf:"bytes,9,opt,name=triggerPriceX18,proto3" json:"triggerPriceX18,omitempty"`
	Expiry            string                 `protobuf:"bytes,10,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Nonce             string                 `protobuf:"bytes,11,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Recipient         string                 `protobuf:"bytes,12,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Signature         string                 `protobuf:"bytes,13,opt,name=signature,proto3" json:"signature,omitempty"`
	Source            string                 `protobuf:"bytes,14,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_rpc_proto_executor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_executor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *CreateOrderRequest) GetSettlementAddress() string {
	if x != nil {
		return x.SettlementAddress
	}
	return ""
}

func (x *CreateOrderRequest) GetOrderHash() string {
	if x != nil {
		return x.OrderHash
	}
	return ""
}

func (x *CreateOrderRequest) GetMaker() string {
	if x != nil {
		return x.Maker
	}
	return ""
}

func (x *CreateOrderRequest) GetInputToken() string {
	if x != nil {
		return x.InputToken
	}
	return ""
}

func (x *CreateOrderRequest) GetOutputToken() string {
	if x != nil {
		return x.OutputToken
	}
	return ""
}

func (x *CreateOrderRequest) GetAmountIn() string {
	if x != nil {
		return x.AmountIn
	}
	return ""
}

func (x *CreateOrderRequest) GetMinAmountOut() string {
	if x != nil {
		return x.MinAmountOut
	}
	return ""
}

func (x *CreateOrderRequest) GetTriggerPriceX18() string {
	if x != nil {
		return x.TriggerPriceX18
	}
	return ""
}

func (x *CreateOrderRequest) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

func (x *CreateOrderRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *CreateOrderRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *CreateOrderRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *CreateOrderRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *GetOrderResponse      `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Notice        *ResponseNotice        `protobuf:"bytes,2,opt,name=notice,proto3" json:"notice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_rpc_proto_executor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_executor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{4}
}

func (x *CreateOrderResponse) GetOrder() *GetOrderResponse {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *CreateOrderResponse) GetNotice() *ResponseNotice {
	if x != nil {
		return x.Notice
	}
	return nil
}

type CancelOrderItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChainId           int64                  `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	SettlementAddress string                 `protobuf:"bytes,2,opt,name=settlementAddress,proto3" json:"settlementAddress,omitempty"`
	OrderHash         string                 `protobuf:"bytes,3,opt,name=orderHash,proto3" json:"orderHash,omitempty"`
	Maker             string                 `protobuf:"bytes,4,opt,name=maker,proto3" json:"maker,omitempty"`
	Reason            string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CancelOrderItem) Reset() {
	*x = CancelOrderItem{}
	mi := &file_rpc_proto_executor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderItem) ProtoMessage() {}

func (x *CancelOrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_executor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderItem.ProtoReflect.Descriptor instead.
func (*CancelOrderItem) Descriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{5}
}

func (x *CancelOrderItem) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *CancelOrderItem) GetSettlementAddress() string {
	if x != nil {
		return x.SettlementAddress
	}
	return ""
}

func (x *CancelOrderItem) GetOrderHash() string {
	if x != nil {
		return x.OrderHash
	}
	return ""
}

func (x *CancelOrderItem) GetMaker() string {
	if x != nil {
		return x.Maker
	}
	return ""
}

func (x *CancelOrderItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelOrdersRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Orders          []*CancelOrderItem     `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Deadline        string                 `protobuf:"bytes,2,opt,name=deadline,proto3" json:"deadline,omitempty"`
	CancelSignature string                 `protobuf:"bytes,3,opt,name=cancelSignature,proto3" json:"cancelSignature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CancelOrdersRequest) Reset() {
	*x = CancelOrdersRequest{}
	mi := &file_rpc_proto_executor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrdersRequest) ProtoMessage() {}

func (x *CancelOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_executor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrdersRequest.ProtoReflect.Descriptor instead.
func (*CancelOrdersRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{6}
}

func (x *CancelOrdersRequest) GetOrders() []*CancelOrderItem {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *CancelOrdersRequest) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *CancelOrdersRequest) GetCancelSignature() string {
	if x != nil {
		return x.CancelSignature
	}
	return ""
}

type CancelOrdersResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChainId           int64                  `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	SettlementAddress string                 `protobuf:"bytes,2,opt,name=settlementAddress,proto3" json:"settlementAddress,omitempty"`
	OrderHash         string                 `protobuf:"bytes,3,opt,name=orderHash,proto3" json:"orderHash,omitempty"`
	Cancelled         bool                   `protobuf:"varint,4,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	Error             string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Code              string                 `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	Message           string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	Hint              string                 `protobuf:"bytes,8,opt,name=hint,proto3" json:"hint,omitempty"`
	Stage             string                 `protobuf:"bytes,9,opt,name=stage,proto3" json:"stage,omitempty"`
	Order             *GetOrderResponse      `protobuf:"bytes,10,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CancelOrdersResult) Reset() {
	*x = CancelOrdersResult{}
	mi := &file_rpc_proto_executor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrdersResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrdersResult) ProtoMessage() {}

func (x *CancelOrdersResult) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_executor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrdersResult.ProtoReflect.Descriptor instead.
func (*CancelOrdersResult) Descriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{7}
}

func (x *CancelOrdersResult) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *CancelOrdersResult) GetSettlementAddress() string {
	if x != nil {
		return x.SettlementAddress
	}
	return ""
}

func (x *CancelOrdersResult) GetOrderHash() string {
	if x != nil {
		return x.OrderHash
	}
	return ""
}

func (x *CancelOrdersResult) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

func (x *CancelOrdersResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CancelOrdersResult) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CancelOrdersResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CancelOrdersResult) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

func (x *CancelOrdersResult) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *CancelOrdersResult) GetOrder() *GetOrderResponse {
	if x != nil {
		return x.Order
	}
	return nil
}

type CancelOrdersResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Total          uint32                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	CancelledCount uint32                 `protobuf:"varint,2,opt,name=cancelledCount,proto3" json:"cancelledCount,omitempty"`
	Results        []*CancelOrdersResult  `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	Notice         *ResponseNotice        `protobuf:"bytes,4,opt,name=notice,proto3" json:"notice,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelOrdersResponse) Reset() {
	*x = CancelOrdersResponse{}
	mi := &file_rpc_proto_executor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrdersResponse) ProtoMessage() {}

func (x *CancelOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_executor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrdersResponse.ProtoReflect.Descriptor instead.
func (*CancelOrdersResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{8}
}

func (x *CancelOrdersResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CancelOrdersResponse) GetCancelledCount() uint32 {
	if x != nil {
		return x.CancelledCount
	}
	return 0
}

func (x *CancelOrdersResponse) GetResults() []*CancelOrdersResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *CancelOrdersResponse) GetNotice() *ResponseNotice {
	if x != nil {
		return x.Notice
	}
	return nil
}

type ApplyOrderEventRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChainId         int64                  `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contractAddress,proto3" json:"contractAddress,omitempty"`
	EventName       string                 `protobuf:"bytes,3,opt,name=eventName,proto3" json:"eventName,omitempty"`
	TxHash          string                 `protobuf:"bytes,4,opt,name=txHash,proto3" json:"txHash,omitempty"`
	BlockNumber     int64                  `protobuf:"varint,5,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	OrderHash       string                 `protobuf:"bytes,6,opt,name=orderHash,proto3" json:"orderHash,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApplyOrderEventRequest) Reset() {
	*x = ApplyOrderEventRequest{}
	mi := &file_rpc_proto_executor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyOrderEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyOrderEventRequest) ProtoMessage() {}

func (x *ApplyOrderEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_executor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyOrderEventRequest.ProtoReflect.Descriptor instead.
func (*ApplyOrderEventRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{9}
}

func (x *ApplyOrderEventRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *ApplyOrderEventRequest) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *ApplyOrderEventRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *ApplyOrderEventRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *ApplyOrderEventRequest) GetBlockNumber() int64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ApplyOrderEventRequest) GetOrderHash() string {
	if x != nil {
		return x.OrderHash
	}
	return ""
}

type ApplyOrderEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *GetOrderResponse      `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Notice        *ResponseNotice        `protobuf:"bytes,2,opt,name=notice,proto3" json:"notice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyOrderEventResponse) Reset() {
	*x = ApplyOrderEventResponse{}
	mi := &file_rpc_proto_executor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyOrderEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyOrderEventResponse) ProtoMessage() {}

func (x *ApplyOrderEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_executor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyOrderEventResponse.ProtoReflect.Descriptor instead.
func (*ApplyOrderEventResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{10}
}

func (x *ApplyOrderEventResponse) GetOrder() *GetOrderResponse {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *ApplyOrderEventResponse) GetNotice() *ResponseNotice {
	if x != nil {
		return x.Notice
	}
	return nil
}

type GetOrderRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChainId           int64                  `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	SettlementAddress string                 `protobuf:"bytes,2,opt,name=settlementAddress,proto3" json:"settlementAddress,omitempty"`
	OrderHash         string                 `protobuf:"bytes,3,opt,name=orderHash,proto3" json:"orderHash,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_rpc_proto_executor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_executor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{11}
}

func (x *GetOrderRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetOrderRequest) GetSettlementAddress() string {
	if x != nil {
		return x.SettlementAddress
	}
	return ""
}

func (x *GetOrderRequest) GetOrderHash() string {
	if x != nil {
		return x.OrderHash
	}
	return ""
}

type GetOrderResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ChainId           int64                  `protobuf:"varint,2,opt,name=chainId,proto3" json:"chainId,omitempty"`
	SettlementAddress string                 `protobuf:"bytes,3,opt,name=settlementAddress,proto3" json:"settlementAddress,omitempty"`
	OrderHash         string                 `protobuf:"bytes,4,opt,name=orderHash,proto3" json:"orderHash,omitempty"`
	Maker             string                 `protobuf:"bytes,5,opt,name=maker,proto3" json:"maker,omitempty"`
	InputToken        string                 `protobuf:"bytes,6,opt,name=inputToken,proto3" json:"inputToken,omitempty"`
	OutputToken       string                 `protobuf:"bytes,7,opt,name=outputToken,proto3" json:"outputToken,omitempty"`
	AmountIn          string                 `protobuf:"bytes,8,opt,name=amountIn,proto3" json:"amountIn,omitempty"`
	MinAmountOut      string                 `protobuf:"bytes,9,opt,name=minAmountOut,proto3" json:"minAmountOut,omitempty"`
	TriggerPriceX18   string                 `protobuf:"bytes,10,opt,name=triggerPriceX18,proto3" json:"triggerPriceX18,omitempty"`
	Expiry            string                 `protobuf:"bytes,11,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Nonce             string                 `protobuf:"bytes,12,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Recipient         string                 `protobuf:"bytes,13,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Source            string                 `protobuf:"bytes,14,opt,name=source,proto3" json:"source,omitempty"`
	Status            string                 `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty"`
	StatusReason      string                 `protobuf:"bytes,16,opt,name=statusReason,proto3" json:"statusReason,omitempty"`
	SubmittedTxHash   string                 `protobuf:"bytes,17,opt,name=submittedTxHash,proto3" json:"submittedTxHash,omitempty"`
	ExecutedTxHash    string                 `protobuf:"bytes,18,opt,name=executedTxHash,proto3" json:"executedTxHash,omitempty"`
	CancelledTxHash   string                 `protobuf:"bytes,19,opt,name=cancelledTxHash,proto3" json:"cancelledTxHash,omitempty"`
	LastCheckedBlock  int64                  `protobuf:"varint,20,opt,name=lastCheckedBlock,proto3" json:"lastCheckedBlock,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,21,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,22,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Notice            *ResponseNotice        `protobuf:"bytes,23,opt,name=notice,proto3" json:"notice,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_rpc_proto_executor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_executor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{12}
}

func (x *GetOrderResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetOrderResponse) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetOrderResponse) GetSettlementAddress() string {
	if x != nil {
		return x.SettlementAddress
	}
	return ""
}

func (x *GetOrderResponse) GetOrderHash() string {
	if x != nil {
		return x.OrderHash
	}
	return ""
}

func (x *GetOrderResponse) GetMaker() string {
	if x != nil {
		return x.Maker
	}
	return ""
}

func (x *GetOrderResponse) GetInputToken() string {
	if x != nil {
		return x.InputToken
	}
	return ""
}

func (x *GetOrderResponse) GetOutputToken() string {
	if x != nil {
		return x.OutputToken
	}
	return ""
}

func (x *GetOrderResponse) GetAmountIn() string {
	if x != nil {
		return x.AmountIn
	}
	return ""
}

func (x *GetOrderResponse) GetMinAmountOut() string {
	if x != nil {
		return x.MinAmountOut
	}
	return ""
}

func (x *GetOrderResponse) GetTriggerPriceX18() string {
	if x != nil {
		return x.TriggerPriceX18
	}
	return ""
}

func (x *GetOrderResponse) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

func (x *GetOrderResponse) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *GetOrderResponse) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *GetOrderResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GetOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetOrderResponse) GetStatusReason() string {
	if x != nil {
		return x.StatusReason
	}
	return ""
}

func (x *GetOrderResponse) GetSubmittedTxHash() string {
	if x != nil {
		return x.SubmittedTxHash
	}
	return ""
}

func (x *GetOrderResponse) GetExecutedTxHash() string {
	if x != nil {
		return x.ExecutedTxHash
	}
	return ""
}

func (x *GetOrderResponse) GetCancelledTxHash() string {
	if x != nil {
		return x.CancelledTxHash
	}
	return ""
}

func (x *GetOrderResponse) GetLastCheckedBlock() int64 {
	if x != nil {
		return x.LastCheckedBlock
	}
	return 0
}

func (x *GetOrderResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetOrderResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GetOrderResponse) GetNotice() *ResponseNotice {
	if x != nil {
		return x.Notice
	}
	return nil
}

var File_rpc_proto_executor_proto protoreflect.FileDescriptor

const file_rpc_proto_executor_proto_rawDesc = "" +
	"\n" +
	"\x18rpc/proto/executor.proto\x12\bexecutor\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"Z\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x120\n" +
	"\x06notice\x18\x02 \x01(\v2\x18.executor.ResponseNoticeR\x06notice\"\x82\x01\n" +
	"\x0eResponseNotice\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x12\n" +
	"\x04hint\x18\x04 \x01(\tR\x04hint\x12\x14\n" +
	"\x05stage\x18\x05 \x01(\tR\x05stage\"\xbe\x03\n" +
	"\x12CreateOrderRequest\x12\x18\n" +
	"\achainId\x18\x01 \x01(\x03R\achainId\x12,\n" +
	"\x11settlementAddress\x18\x02 \x01(\tR\x11settlementAddress\x12\x1c\n" +
	"\torderHash\x18\x03 \x01(\tR\torderHash\x12\x14\n" +
	"\x05maker\x18\x04 \x01(\tR\x05maker\x12\x1e\n" +
	"\n" +
	"inputToken\x18\x05 \x01(\tR\n" +
	"inputToken\x12 \n" +
	"\voutputToken\x18\x06 \x01(\tR\voutputToken\x12\x1a\n" +
	"\bamountIn\x18\a \x01(\tR\bamountIn\x12\"\n" +
	"\fminAmountOut\x18\b \x01(\tR\fminAmountOut\x12(\n" +
	"\x0ftriggerPriceX18\x18\t \x01(\tR\x0ftriggerPriceX18\x12\x16\n" +
	"\x06expiry\x18\n" +
	" \x01(\tR\x06expiry\x12\x14\n" +
	"\x05nonce\x18\v \x01(\tR\x05nonce\x12\x1c\n" +
	"\trecipient\x18\f \x01(\tR\trecipient\x12\x1c\n" +
	"\tsignature\x18\r \x01(\tR\tsignature\x12\x16\n" +
	"\x06source\x18\x0e \x01(\tR\x06source\"y\n" +
	"\x13CreateOrderResponse\x120\n" +
	"\x05order\x18\x01 \x01(\v2\x1a.executor.GetOrderResponseR\x05order\x120\n" +
	"\x06notice\x18\x02 \x01(\v2\x18.executor.ResponseNoticeR\x06notice\"\xa5\x01\n" +
	"\x0fCancelOrderItem\x12\x18\n" +
	"\achainId\x18\x01 \x01(\x03R\achainId\x12,\n" +
	"\x11settlementAddress\x18\x02 \x01(\tR\x11settlementAddress\x12\x1c\n" +
	"\torderHash\x18\x03 \x01(\tR\torderHash\x12\x14\n" +
	"\x05maker\x18\x04 \x01(\tR\x05maker\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\x8e\x01\n" +
	"\x13CancelOrdersRequest\x121\n" +
	"\x06orders\x18\x01 \x03(\v2\x19.executor.CancelOrderItemR\x06orders\x12\x1a\n" +
	"\bdeadline\x18\x02 \x01(\tR\bdeadline\x12(\n" +
	"\x0fcancelSignature\x18\x03 \x01(\tR\x0fcancelSignature\"\xb8\x02\n" +
	"\x12CancelOrdersResult\x12\x18\n" +
	"\achainId\x18\x01 \x01(\x03R\achainId\x12,\n" +
	"\x11settlementAddress\x18\x02 \x01(\tR\x11settlementAddress\x12\x1c\n" +
	"\torderHash\x18\x03 \x01(\tR\torderHash\x12\x1c\n" +
	"\tcancelled\x18\x04 \x01(\bR\tcancelled\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x12\n" +
	"\x04code\x18\x06 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12\x12\n" +
	"\x04hint\x18\b \x01(\tR\x04hint\x12\x14\n" +
	"\x05stage\x18\t \x01(\tR\x05stage\x120\n" +
	"\x05order\x18\n" +
	" \x01(\v2\x1a.executor.GetOrderResponseR\x05order\"\xbe\x01\n" +
	"\x14CancelOrdersResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\rR\x05total\x12&\n" +
	"\x0ecancelledCount\x18\x02 \x01(\rR\x0ecancelledCount\x126\n" +
	"\aresults\x18\x03 \x03(\v2\x1c.executor.CancelOrdersResultR\aresults\x120\n" +
	"\x06notice\x18\x04 \x01(\v2\x18.executor.ResponseNoticeR\x06notice\"\xd2\x01\n" +
	"\x16ApplyOrderEventRequest\x12\x18\n" +
	"\achainId\x18\x01 \x01(\x03R\achainId\x12(\n" +
	"\x0fcontractAddress\x18\x02 \x01(\tR\x0fcontractAddress\x12\x1c\n" +
	"\teventName\x18\x03 \x01(\tR\teventName\x12\x16\n" +
	"\x06txHash\x18\x04 \x01(\tR\x06txHash\x12 \n" +
	"\vblockNumber\x18\x05 \x01(\x03R\vblockNumber\x12\x1c\n" +
	"\torderHash\x18\x06 \x01(\tR\torderHash\"}\n" +
	"\x17ApplyOrderEventResponse\x120\n" +
	"\x05order\x18\x01 \x01(\v2\x1a.executor.GetOrderResponseR\x05order\x120\n" +
	"\x06notice\x18\x02 \x01(\v2\x18.executor.ResponseNoticeR\x06notice\"w\n" +
	"\x0fGetOrderRequest\x12\x18\n" +
	"\achainId\x18\x01 \x01(\x03R\achainId\x12,\n" +
	"\x11settlementAddress\x18\x02 \x01(\tR\x11settlementAddress\x12\x1c\n" +
	"\torderHash\x18\x03 \x01(\tR\torderHash\"\x80\x06\n" +
	"\x10GetOrderResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\achainId\x18\x02 \x01(\x03R\achainId\x12,\n" +
	"\x11settlementAddress\x18\x03 \x01(\tR\x11settlementAddress\x12\x1c\n" +
	"\torderHash\x18\x04 \x01(\tR\torderHash\x12\x14\n" +
	"\x05maker\x18\x05 \x01(\tR\x05maker\x12\x1e\n" +
	"\n" +
	"inputToken\x18\x06 \x01(\tR\n" +
	"inputToken\x12 \n" +
	"\voutputToken\x18\a \x01(\tR\voutputToken\x12\x1a\n" +
	"\bamountIn\x18\b \x01(\tR\bamountIn\x12\"\n" +
	"\fminAmountOut\x18\t \x01(\tR\fminAmountOut\x12(\n" +
	"\x0ftriggerPriceX18\x18\n" +
	" \x01(\tR\x0ftriggerPriceX18\x12\x16\n" +
	"\x06expiry\x18\v \x01(\tR\x06expiry\x12\x14\n" +
	"\x05nonce\x18\f \x01(\tR\x05nonce\x12\x1c\n" +
	"\trecipient\x18\r \x01(\tR\trecipient\x12\x16\n" +
	"\x06source\x18\x0e \x01(\tR\x06source\x12\x16\n" +
	"\x06status\x18\x0f \x01(\tR\x06status\x12\"\n" +
	"\fstatusReason\x18\x10 \x01(\tR\fstatusReason\x12(\n" +
	"\x0fsubmittedTxHash\x18\x11 \x01(\tR\x0fsubmittedTxHash\x12&\n" +
	"\x0eexecutedTxHash\x18\x12 \x01(\tR\x0eexecutedTxHash\x12(\n" +
	"\x0fcancelledTxHash\x18\x13 \x01(\tR\x0fcancelledTxHash\x12*\n" +
	"\x10lastCheckedBlock\x18\x14 \x01(\x03R\x10lastCheckedBlock\x12\x1c\n" +
	"\tcreatedAt\x18\x15 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x16 \x01(\tR\tupdatedAt\x120\n" +
	"\x06notice\x18\x17 \x01(\v2\x18.executor.ResponseNoticeR\x06notice2\xf7\x02\n" +
	"\bExecutor\x125\n" +
	"\x04Ping\x12\x15.executor.PingRequest\x1a\x16.executor.PingResponse\x12J\n" +
	"\vCreateOrder\x12\x1c.executor.CreateOrderRequest\x1a\x1d.executor.CreateOrderResponse\x12M\n" +
	"\fCancelOrders\x12\x1d.executor.CancelOrdersRequest\x1a\x1e.executor.CancelOrdersResponse\x12V\n" +
	"\x0fApplyOrderEvent\x12 .executor.ApplyOrderEventRequest\x1a!.executor.ApplyOrderEventResponse\x12A\n" +
	"\bGetOrder\x12\x19.executor.GetOrderRequest\x1a\x1a.executor.GetOrderResponseB\fZ\n" +
	"./executorb\x06proto3"

var (
	file_rpc_proto_executor_proto_rawDescOnce sync.Once
	file_rpc_proto_executor_proto_rawDescData []byte
)

func file_rpc_proto_executor_proto_rawDescGZIP() []byte {
	file_rpc_proto_executor_proto_rawDescOnce.Do(func() {
		file_rpc_proto_executor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_proto_executor_proto_rawDesc), len(file_rpc_proto_executor_proto_rawDesc)))
	})
	return file_rpc_proto_executor_proto_rawDescData
}

var file_rpc_proto_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_rpc_proto_executor_proto_goTypes = []any{
	(*PingRequest)(nil),             // 0: executor.PingRequest
	(*PingResponse)(nil),            // 1: executor.PingResponse
	(*ResponseNotice)(nil),          // 2: executor.ResponseNotice
	(*CreateOrderRequest)(nil),      // 3: executor.CreateOrderRequest
	(*CreateOrderResponse)(nil),     // 4: executor.CreateOrderResponse
	(*CancelOrderItem)(nil),         // 5: executor.CancelOrderItem
	(*CancelOrdersRequest)(nil),     // 6: executor.CancelOrdersRequest
	(*CancelOrdersResult)(nil),      // 7: executor.CancelOrdersResult
	(*CancelOrdersResponse)(nil),    // 8: executor.CancelOrdersResponse
	(*ApplyOrderEventRequest)(nil),  // 9: executor.ApplyOrderEventRequest
	(*ApplyOrderEventResponse)(nil), // 10: executor.ApplyOrderEventResponse
	(*GetOrderRequest)(nil),         // 11: executor.GetOrderRequest
	(*GetOrderResponse)(nil),        // 12: executor.GetOrderResponse
}
var file_rpc_proto_executor_proto_depIdxs = []int32{
	2,  // 0: executor.PingResponse.notice:type_name -> executor.ResponseNotice
	12, // 1: executor.CreateOrderResponse.order:type_name -> executor.GetOrderResponse
	2,  // 2: executor.CreateOrderResponse.notice:type_name -> executor.ResponseNotice
	5,  // 3: executor.CancelOrdersRequest.orders:type_name -> executor.CancelOrderItem
	12, // 4: executor.CancelOrdersResult.order:type_name -> executor.GetOrderResponse
	7,  // 5: executor.CancelOrdersResponse.results:type_name -> executor.CancelOrdersResult
	2,  // 6: executor.CancelOrdersResponse.notice:type_name -> executor.ResponseNotice
	12, // 7: executor.ApplyOrderEventResponse.order:type_name -> executor.GetOrderResponse
	2,  // 8: executor.ApplyOrderEventResponse.notice:type_name -> executor.ResponseNotice
	2,  // 9: executor.GetOrderResponse.notice:type_name -> executor.ResponseNotice
	0,  // 10: executor.Executor.Ping:input_type -> executor.PingRequest
	3,  // 11: executor.Executor.CreateOrder:input_type -> executor.CreateOrderRequest
	6,  // 12: executor.Executor.CancelOrders:input_type -> executor.CancelOrdersRequest
	9,  // 13: executor.Executor.ApplyOrderEvent:input_type -> executor.ApplyOrderEventRequest
	11, // 14: executor.Executor.GetOrder:input_type -> executor.GetOrderRequest
	1,  // 15: executor.Executor.Ping:output_type -> executor.PingResponse
	4,  // 16: executor.Executor.CreateOrder:output_type -> executor.CreateOrderResponse
	8,  // 17: executor.Executor.CancelOrders:output_type -> executor.CancelOrdersResponse
	10, // 18: executor.Executor.ApplyOrderEvent:output_type -> executor.ApplyOrderEventResponse
	12, // 19: executor.Executor.GetOrder:output_type -> executor.GetOrderResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_rpc_proto_executor_proto_init() }
func file_rpc_proto_executor_proto_init() {
	if File_rpc_proto_executor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proto_executor_proto_rawDesc), len(file_rpc_proto_executor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proto_executor_proto_goTypes,
		DependencyIndexes: file_rpc_proto_executor_proto_depIdxs,
		MessageInfos:      file_rpc_proto_executor_proto_msgTypes,
	}.Build()
	File_rpc_proto_executor_proto = out.File
	file_rpc_proto_executor_proto_goTypes = nil
	file_rpc_proto_executor_proto_depIdxs = nil
}
