// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: rpc/proto/executor.proto

package executor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteQuoteType int32

const (
	RouteQuoteType_ROUTE_QUOTE_TYPE_UNSPECIFIED  RouteQuoteType = 0
	RouteQuoteType_ROUTE_QUOTE_TYPE_EXACT_INPUT  RouteQuoteType = 1
	RouteQuoteType_ROUTE_QUOTE_TYPE_EXACT_OUTPUT RouteQuoteType = 2
)

// Enum value maps for RouteQuoteType.
var (
	RouteQuoteType_name = map[int32]string{
		0: "ROUTE_QUOTE_TYPE_UNSPECIFIED",
		1: "ROUTE_QUOTE_TYPE_EXACT_INPUT",
		2: "ROUTE_QUOTE_TYPE_EXACT_OUTPUT",
	}
	RouteQuoteType_value = map[string]int32{
		"ROUTE_QUOTE_TYPE_UNSPECIFIED":  0,
		"ROUTE_QUOTE_TYPE_EXACT_INPUT":  1,
		"ROUTE_QUOTE_TYPE_EXACT_OUTPUT": 2,
	}
)

func (x RouteQuoteType) Enum() *RouteQuoteType {
	p := new(RouteQuoteType)
	*p = x
	return p
}

func (x RouteQuoteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteQuoteType) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_executor_proto_enumTypes[0].Descriptor()
}

func (RouteQuoteType) Type() protoreflect.EnumType {
	return &file_rpc_proto_executor_proto_enumTypes[0]
}

func (x RouteQuoteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteQuoteType.Descriptor instead.
func (RouteQuoteType) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{0}
}

type ResponseNotice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Hint          string                 `protobuf:"bytes,4,opt,name=hint,proto3" json:"hint,omitempty"`
	Stage         string                 `protobuf:"bytes,5,opt,name=stage,proto3" json:"stage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseNotice) Reset() {
	*x = ResponseNotice{}
	mi := &file_rpc_proto_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseNotice) ProtoMessage() {}

func (x *ResponseNotice) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseNotice.ProtoReflect.Descriptor instead.
func (*ResponseNotice) Descriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseNotice) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResponseNotice) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseNotice) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseNotice) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

func (x *ResponseNotice) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

type CreateOrderRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ChainId              int64                  `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	SettlementAddress    string                 `protobuf:"bytes,2,opt,name=settlementAddress,proto3" json:"settlementAddress,omitempty"`
	OrderHash            string                 `protobuf:"bytes,3,opt,name=orderHash,proto3" json:"orderHash,omitempty"`
	Maker                string                 `protobuf:"bytes,4,opt,name=maker,proto3" json:"maker,omitempty"`
	InputToken           string                 `protobuf:"bytes,5,opt,name=inputToken,proto3" json:"inputToken,omitempty"`
	OutputToken          string                 `protobuf:"bytes,6,opt,name=outputToken,proto3" json:"outputToken,omitempty"`
	AmountIn             string                 `protobuf:"bytes,7,opt,name=amountIn,proto3" json:"amountIn,omitempty"`
	MinAmountOut         string                 `protobuf:"bytes,8,opt,name=minAmountOut,proto3" json:"minAmountOut,omitempty"`
	TriggerPriceX18      string                 `protobuf:"bytes,9,opt,name=triggerPriceX18,proto3" json:"triggerPriceX18,omitempty"`
	Expiry               string                 `protobuf:"bytes,10,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Nonce                string                 `protobuf:"bytes,11,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Recipient            string                 `protobuf:"bytes,12,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Signature            string                 `protobuf:"bytes,13,opt,name=signature,proto3" json:"signature,omitempty"`
	Source               string                 `protobuf:"bytes,14,opt,name=source,proto3" json:"source,omitempty"`
	MaxExecutorRewardBps string                 `protobuf:"bytes,15,opt,name=maxExecutorRewardBps,proto3" json:"maxExecutorRewardBps,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_rpc_proto_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *CreateOrderRequest) GetSettlementAddress() string {
	if x != nil {
		return x.SettlementAddress
	}
	return ""
}

func (x *CreateOrderRequest) GetOrderHash() string {
	if x != nil {
		return x.OrderHash
	}
	return ""
}

func (x *CreateOrderRequest) GetMaker() string {
	if x != nil {
		return x.Maker
	}
	return ""
}

func (x *CreateOrderRequest) GetInputToken() string {
	if x != nil {
		return x.InputToken
	}
	return ""
}

func (x *CreateOrderRequest) GetOutputToken() string {
	if x != nil {
		return x.OutputToken
	}
	return ""
}

func (x *CreateOrderRequest) GetAmountIn() string {
	if x != nil {
		return x.AmountIn
	}
	return ""
}

func (x *CreateOrderRequest) GetMinAmountOut() string {
	if x != nil {
		return x.MinAmountOut
	}
	return ""
}

func (x *CreateOrderRequest) GetTriggerPriceX18() string {
	if x != nil {
		return x.TriggerPriceX18
	}
	return ""
}

func (x *CreateOrderRequest) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

func (x *CreateOrderRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *CreateOrderRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *CreateOrderRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *CreateOrderRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CreateOrderRequest) GetMaxExecutorRewardBps() string {
	if x != nil {
		return x.MaxExecutorRewardBps
	}
	return ""
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *GetOrderResponse      `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Notice        *ResponseNotice        `protobuf:"bytes,2,opt,name=notice,proto3" json:"notice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_rpc_proto_executor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_executor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderResponse) GetOrder() *GetOrderResponse {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *CreateOrderResponse) GetNotice() *ResponseNotice {
	if x != nil {
		return x.Notice
	}
	return nil
}

type CancelOrderItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChainId           int64                  `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	SettlementAddress string                 `protobuf:"bytes,2,opt,name=settlementAddress,proto3" json:"settlementAddress,omitempty"`
	OrderHash         string                 `protobuf:"bytes,3,opt,name=orderHash,proto3" json:"orderHash,omitempty"`
	Maker             string                 `protobuf:"bytes,4,opt,name=maker,proto3" json:"maker,omitempty"`
	Reason            string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CancelOrderItem) Reset() {
	*x = CancelOrderItem{}
	mi := &file_rpc_proto_executor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderItem) ProtoMessage() {}

func (x *CancelOrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_executor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderItem.ProtoReflect.Descriptor instead.
func (*CancelOrderItem) Descriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{3}
}

func (x *CancelOrderItem) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *CancelOrderItem) GetSettlementAddress() string {
	if x != nil {
		return x.SettlementAddress
	}
	return ""
}

func (x *CancelOrderItem) GetOrderHash() string {
	if x != nil {
		return x.OrderHash
	}
	return ""
}

func (x *CancelOrderItem) GetMaker() string {
	if x != nil {
		return x.Maker
	}
	return ""
}

func (x *CancelOrderItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*CancelOrderItem     `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	CancelTxHash  string                 `protobuf:"bytes,2,opt,name=cancelTxHash,proto3" json:"cancelTxHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrdersRequest) Reset() {
	*x = CancelOrdersRequest{}
	mi := &file_rpc_proto_executor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrdersRequest) ProtoMessage() {}

func (x *CancelOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_executor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrdersRequest.ProtoReflect.Descriptor instead.
func (*CancelOrdersRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{4}
}

func (x *CancelOrdersRequest) GetOrders() []*CancelOrderItem {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *CancelOrdersRequest) GetCancelTxHash() string {
	if x != nil {
		return x.CancelTxHash
	}
	return ""
}

type CancelOrdersResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChainId           int64                  `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	SettlementAddress string                 `protobuf:"bytes,2,opt,name=settlementAddress,proto3" json:"settlementAddress,omitempty"`
	OrderHash         string                 `protobuf:"bytes,3,opt,name=orderHash,proto3" json:"orderHash,omitempty"`
	Cancelled         bool                   `protobuf:"varint,4,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	Error             string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Code              string                 `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	Message           string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	Hint              string                 `protobuf:"bytes,8,opt,name=hint,proto3" json:"hint,omitempty"`
	Stage             string                 `protobuf:"bytes,9,opt,name=stage,proto3" json:"stage,omitempty"`
	Order             *GetOrderResponse      `protobuf:"bytes,10,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CancelOrdersResult) Reset() {
	*x = CancelOrdersResult{}
	mi := &file_rpc_proto_executor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrdersResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrdersResult) ProtoMessage() {}

func (x *CancelOrdersResult) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_executor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrdersResult.ProtoReflect.Descriptor instead.
func (*CancelOrdersResult) Descriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{5}
}

func (x *CancelOrdersResult) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *CancelOrdersResult) GetSettlementAddress() string {
	if x != nil {
		return x.SettlementAddress
	}
	return ""
}

func (x *CancelOrdersResult) GetOrderHash() string {
	if x != nil {
		return x.OrderHash
	}
	return ""
}

func (x *CancelOrdersResult) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

func (x *CancelOrdersResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CancelOrdersResult) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CancelOrdersResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CancelOrdersResult) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

func (x *CancelOrdersResult) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *CancelOrdersResult) GetOrder() *GetOrderResponse {
	if x != nil {
		return x.Order
	}
	return nil
}

type CancelOrdersResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Total          uint32                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	CancelledCount uint32                 `protobuf:"varint,2,opt,name=cancelledCount,proto3" json:"cancelledCount,omitempty"`
	Results        []*CancelOrdersResult  `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	Notice         *ResponseNotice        `protobuf:"bytes,4,opt,name=notice,proto3" json:"notice,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelOrdersResponse) Reset() {
	*x = CancelOrdersResponse{}
	mi := &file_rpc_proto_executor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrdersResponse) ProtoMessage() {}

func (x *CancelOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_executor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrdersResponse.ProtoReflect.Descriptor instead.
func (*CancelOrdersResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{6}
}

func (x *CancelOrdersResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CancelOrdersResponse) GetCancelledCount() uint32 {
	if x != nil {
		return x.CancelledCount
	}
	return 0
}

func (x *CancelOrdersResponse) GetResults() []*CancelOrdersResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *CancelOrdersResponse) GetNotice() *ResponseNotice {
	if x != nil {
		return x.Notice
	}
	return nil
}

type GetOrderRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChainId           int64                  `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	SettlementAddress string                 `protobuf:"bytes,2,opt,name=settlementAddress,proto3" json:"settlementAddress,omitempty"`
	OrderHash         string                 `protobuf:"bytes,3,opt,name=orderHash,proto3" json:"orderHash,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_rpc_proto_executor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_executor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrderRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetOrderRequest) GetSettlementAddress() string {
	if x != nil {
		return x.SettlementAddress
	}
	return ""
}

func (x *GetOrderRequest) GetOrderHash() string {
	if x != nil {
		return x.OrderHash
	}
	return ""
}

type GetOrderResponse struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Id                         uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ChainId                    int64                  `protobuf:"varint,2,opt,name=chainId,proto3" json:"chainId,omitempty"`
	SettlementAddress          string                 `protobuf:"bytes,3,opt,name=settlementAddress,proto3" json:"settlementAddress,omitempty"`
	OrderHash                  string                 `protobuf:"bytes,4,opt,name=orderHash,proto3" json:"orderHash,omitempty"`
	Maker                      string                 `protobuf:"bytes,5,opt,name=maker,proto3" json:"maker,omitempty"`
	InputToken                 string                 `protobuf:"bytes,6,opt,name=inputToken,proto3" json:"inputToken,omitempty"`
	OutputToken                string                 `protobuf:"bytes,7,opt,name=outputToken,proto3" json:"outputToken,omitempty"`
	AmountIn                   string                 `protobuf:"bytes,8,opt,name=amountIn,proto3" json:"amountIn,omitempty"`
	MinAmountOut               string                 `protobuf:"bytes,9,opt,name=minAmountOut,proto3" json:"minAmountOut,omitempty"`
	TriggerPriceX18            string                 `protobuf:"bytes,10,opt,name=triggerPriceX18,proto3" json:"triggerPriceX18,omitempty"`
	Expiry                     string                 `protobuf:"bytes,11,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Nonce                      string                 `protobuf:"bytes,12,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Recipient                  string                 `protobuf:"bytes,13,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Source                     string                 `protobuf:"bytes,14,opt,name=source,proto3" json:"source,omitempty"`
	Status                     string                 `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty"`
	StatusReason               string                 `protobuf:"bytes,16,opt,name=statusReason,proto3" json:"statusReason,omitempty"`
	SubmittedTxHash            string                 `protobuf:"bytes,17,opt,name=submittedTxHash,proto3" json:"submittedTxHash,omitempty"`
	ExecutedTxHash             string                 `protobuf:"bytes,18,opt,name=executedTxHash,proto3" json:"executedTxHash,omitempty"`
	CancelledTxHash            string                 `protobuf:"bytes,19,opt,name=cancelledTxHash,proto3" json:"cancelledTxHash,omitempty"`
	LastCheckedBlock           int64                  `protobuf:"varint,20,opt,name=lastCheckedBlock,proto3" json:"lastCheckedBlock,omitempty"`
	CreatedAt                  string                 `protobuf:"bytes,21,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt                  string                 `protobuf:"bytes,22,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Notice                     *ResponseNotice        `protobuf:"bytes,23,opt,name=notice,proto3" json:"notice,omitempty"`
	MaxExecutorRewardBps       string                 `protobuf:"bytes,24,opt,name=maxExecutorRewardBps,proto3" json:"maxExecutorRewardBps,omitempty"`
	ExecutorFeeToken           string                 `protobuf:"bytes,25,opt,name=executorFeeToken,proto3" json:"executorFeeToken,omitempty"`
	EstimatedGasUsed           string                 `protobuf:"bytes,26,opt,name=estimatedGasUsed,proto3" json:"estimatedGasUsed,omitempty"`
	GasPriceAtQuote            string                 `protobuf:"bytes,27,opt,name=gasPriceAtQuote,proto3" json:"gasPriceAtQuote,omitempty"`
	RewardQuoteAt              string                 `protobuf:"bytes,28,opt,name=rewardQuoteAt,proto3" json:"rewardQuoteAt,omitempty"`
	LastRequiredExecutorReward string                 `protobuf:"bytes,29,opt,name=lastRequiredExecutorReward,proto3" json:"lastRequiredExecutorReward,omitempty"`
	LastRewardCheckAt          string                 `protobuf:"bytes,30,opt,name=lastRewardCheckAt,proto3" json:"lastRewardCheckAt,omitempty"`
	LastExecutionCheckAt       string                 `protobuf:"bytes,31,opt,name=lastExecutionCheckAt,proto3" json:"lastExecutionCheckAt,omitempty"`
	LastBlockReason            string                 `protobuf:"bytes,32,opt,name=lastBlockReason,proto3" json:"lastBlockReason,omitempty"`
	SettledAmountOut           string                 `protobuf:"bytes,33,opt,name=settledAmountOut,proto3" json:"settledAmountOut,omitempty"`
	SettledExecutorReward      string                 `protobuf:"bytes,34,opt,name=settledExecutorReward,proto3" json:"settledExecutorReward,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_rpc_proto_executor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_executor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrderResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetOrderResponse) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetOrderResponse) GetSettlementAddress() string {
	if x != nil {
		return x.SettlementAddress
	}
	return ""
}

func (x *GetOrderResponse) GetOrderHash() string {
	if x != nil {
		return x.OrderHash
	}
	return ""
}

func (x *GetOrderResponse) GetMaker() string {
	if x != nil {
		return x.Maker
	}
	return ""
}

func (x *GetOrderResponse) GetInputToken() string {
	if x != nil {
		return x.InputToken
	}
	return ""
}

func (x *GetOrderResponse) GetOutputToken() string {
	if x != nil {
		return x.OutputToken
	}
	return ""
}

func (x *GetOrderResponse) GetAmountIn() string {
	if x != nil {
		return x.AmountIn
	}
	return ""
}

func (x *GetOrderResponse) GetMinAmountOut() string {
	if x != nil {
		return x.MinAmountOut
	}
	return ""
}

func (x *GetOrderResponse) GetTriggerPriceX18() string {
	if x != nil {
		return x.TriggerPriceX18
	}
	return ""
}

func (x *GetOrderResponse) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

func (x *GetOrderResponse) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *GetOrderResponse) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *GetOrderResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GetOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetOrderResponse) GetStatusReason() string {
	if x != nil {
		return x.StatusReason
	}
	return ""
}

func (x *GetOrderResponse) GetSubmittedTxHash() string {
	if x != nil {
		return x.SubmittedTxHash
	}
	return ""
}

func (x *GetOrderResponse) GetExecutedTxHash() string {
	if x != nil {
		return x.ExecutedTxHash
	}
	return ""
}

func (x *GetOrderResponse) GetCancelledTxHash() string {
	if x != nil {
		return x.CancelledTxHash
	}
	return ""
}

func (x *GetOrderResponse) GetLastCheckedBlock() int64 {
	if x != nil {
		return x.LastCheckedBlock
	}
	return 0
}

func (x *GetOrderResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetOrderResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GetOrderResponse) GetNotice() *ResponseNotice {
	if x != nil {
		return x.Notice
	}
	return nil
}

func (x *GetOrderResponse) GetMaxExecutorRewardBps() string {
	if x != nil {
		return x.MaxExecutorRewardBps
	}
	return ""
}

func (x *GetOrderResponse) GetExecutorFeeToken() string {
	if x != nil {
		return x.ExecutorFeeToken
	}
	return ""
}

func (x *GetOrderResponse) GetEstimatedGasUsed() string {
	if x != nil {
		return x.EstimatedGasUsed
	}
	return ""
}

func (x *GetOrderResponse) GetGasPriceAtQuote() string {
	if x != nil {
		return x.GasPriceAtQuote
	}
	return ""
}

func (x *GetOrderResponse) GetRewardQuoteAt() string {
	if x != nil {
		return x.RewardQuoteAt
	}
	return ""
}

func (x *GetOrderResponse) GetLastRequiredExecutorReward() string {
	if x != nil {
		return x.LastRequiredExecutorReward
	}
	return ""
}

func (x *GetOrderResponse) GetLastRewardCheckAt() string {
	if x != nil {
		return x.LastRewardCheckAt
	}
	return ""
}

func (x *GetOrderResponse) GetLastExecutionCheckAt() string {
	if x != nil {
		return x.LastExecutionCheckAt
	}
	return ""
}

func (x *GetOrderResponse) GetLastBlockReason() string {
	if x != nil {
		return x.LastBlockReason
	}
	return ""
}

func (x *GetOrderResponse) GetSettledAmountOut() string {
	if x != nil {
		return x.SettledAmountOut
	}
	return ""
}

func (x *GetOrderResponse) GetSettledExecutorReward() string {
	if x != nil {
		return x.SettledExecutorReward
	}
	return ""
}

type GetBestRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       int64                  `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	TokenIn       string                 `protobuf:"bytes,2,opt,name=tokenIn,proto3" json:"tokenIn,omitempty"`
	TokenOut      string                 `protobuf:"bytes,3,opt,name=tokenOut,proto3" json:"tokenOut,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	MaxHops       uint32                 `protobuf:"varint,5,opt,name=maxHops,proto3" json:"maxHops,omitempty"`
	QuoteType     RouteQuoteType         `protobuf:"varint,6,opt,name=quoteType,proto3,enum=executor.RouteQuoteType" json:"quoteType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBestRouteRequest) Reset() {
	*x = GetBestRouteRequest{}
	mi := &file_rpc_proto_executor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBestRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBestRouteRequest) ProtoMessage() {}

func (x *GetBestRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_executor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBestRouteRequest.ProtoReflect.Descriptor instead.
func (*GetBestRouteRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{9}
}

func (x *GetBestRouteRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetBestRouteRequest) GetTokenIn() string {
	if x != nil {
		return x.TokenIn
	}
	return ""
}

func (x *GetBestRouteRequest) GetTokenOut() string {
	if x != nil {
		return x.TokenOut
	}
	return ""
}

func (x *GetBestRouteRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *GetBestRouteRequest) GetMaxHops() uint32 {
	if x != nil {
		return x.MaxHops
	}
	return 0
}

func (x *GetBestRouteRequest) GetQuoteType() RouteQuoteType {
	if x != nil {
		return x.QuoteType
	}
	return RouteQuoteType_ROUTE_QUOTE_TYPE_UNSPECIFIED
}

type RoutePath struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Tokens               []string               `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	Hops                 uint32                 `protobuf:"varint,2,opt,name=hops,proto3" json:"hops,omitempty"`
	AmountIn             string                 `protobuf:"bytes,3,opt,name=amountIn,proto3" json:"amountIn,omitempty"`
	AmountOut            string                 `protobuf:"bytes,4,opt,name=amountOut,proto3" json:"amountOut,omitempty"`
	GasEstimate          uint64                 `protobuf:"varint,5,opt,name=gasEstimate,proto3" json:"gasEstimate,omitempty"`
	GasCostInInputToken  string                 `protobuf:"bytes,6,opt,name=gasCostInInputToken,proto3" json:"gasCostInInputToken,omitempty"`
	GasCostInOutputToken string                 `protobuf:"bytes,7,opt,name=gasCostInOutputToken,proto3" json:"gasCostInOutputToken,omitempty"`
	GasAdjustedAmountIn  string                 `protobuf:"bytes,8,opt,name=gasAdjustedAmountIn,proto3" json:"gasAdjustedAmountIn,omitempty"`
	GasAdjustedAmountOut string                 `protobuf:"bytes,9,opt,name=gasAdjustedAmountOut,proto3" json:"gasAdjustedAmountOut,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RoutePath) Reset() {
	*x = RoutePath{}
	mi := &file_rpc_proto_executor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutePath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutePath) ProtoMessage() {}

func (x *RoutePath) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_executor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutePath.ProtoReflect.Descriptor instead.
func (*RoutePath) Descriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{10}
}

func (x *RoutePath) GetTokens() []string {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *RoutePath) GetHops() uint32 {
	if x != nil {
		return x.Hops
	}
	return 0
}

func (x *RoutePath) GetAmountIn() string {
	if x != nil {
		return x.AmountIn
	}
	return ""
}

func (x *RoutePath) GetAmountOut() string {
	if x != nil {
		return x.AmountOut
	}
	return ""
}

func (x *RoutePath) GetGasEstimate() uint64 {
	if x != nil {
		return x.GasEstimate
	}
	return 0
}

func (x *RoutePath) GetGasCostInInputToken() string {
	if x != nil {
		return x.GasCostInInputToken
	}
	return ""
}

func (x *RoutePath) GetGasCostInOutputToken() string {
	if x != nil {
		return x.GasCostInOutputToken
	}
	return ""
}

func (x *RoutePath) GetGasAdjustedAmountIn() string {
	if x != nil {
		return x.GasAdjustedAmountIn
	}
	return ""
}

func (x *RoutePath) GetGasAdjustedAmountOut() string {
	if x != nil {
		return x.GasAdjustedAmountOut
	}
	return ""
}

type RouteQuote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuoteType     RouteQuoteType         `protobuf:"varint,1,opt,name=quoteType,proto3,enum=executor.RouteQuoteType" json:"quoteType,omitempty"`
	AmountIn      string                 `protobuf:"bytes,2,opt,name=amountIn,proto3" json:"amountIn,omitempty"`
	AmountOut     string                 `protobuf:"bytes,3,opt,name=amountOut,proto3" json:"amountOut,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteQuote) Reset() {
	*x = RouteQuote{}
	mi := &file_rpc_proto_executor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteQuote) ProtoMessage() {}

func (x *RouteQuote) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_executor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteQuote.ProtoReflect.Descriptor instead.
func (*RouteQuote) Descriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{11}
}

func (x *RouteQuote) GetQuoteType() RouteQuoteType {
	if x != nil {
		return x.QuoteType
	}
	return RouteQuoteType_ROUTE_QUOTE_TYPE_UNSPECIFIED
}

func (x *RouteQuote) GetAmountIn() string {
	if x != nil {
		return x.AmountIn
	}
	return ""
}

func (x *RouteQuote) GetAmountOut() string {
	if x != nil {
		return x.AmountOut
	}
	return ""
}

type RouteView struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PathTokens           []string               `protobuf:"bytes,1,rep,name=pathTokens,proto3" json:"pathTokens,omitempty"`
	ExecutionPath        []string               `protobuf:"bytes,2,rep,name=executionPath,proto3" json:"executionPath,omitempty"`
	Hops                 uint32                 `protobuf:"varint,3,opt,name=hops,proto3" json:"hops,omitempty"`
	IsDirect             bool                   `protobuf:"varint,4,opt,name=isDirect,proto3" json:"isDirect,omitempty"`
	IsMultiHop           bool                   `protobuf:"varint,5,opt,name=isMultiHop,proto3" json:"isMultiHop,omitempty"`
	AmountIn             string                 `protobuf:"bytes,6,opt,name=amountIn,proto3" json:"amountIn,omitempty"`
	AmountOut            string                 `protobuf:"bytes,7,opt,name=amountOut,proto3" json:"amountOut,omitempty"`
	GasEstimate          uint64                 `protobuf:"varint,8,opt,name=gasEstimate,proto3" json:"gasEstimate,omitempty"`
	GasCostInInputToken  string                 `protobuf:"bytes,9,opt,name=gasCostInInputToken,proto3" json:"gasCostInInputToken,omitempty"`
	GasCostInOutputToken string                 `protobuf:"bytes,10,opt,name=gasCostInOutputToken,proto3" json:"gasCostInOutputToken,omitempty"`
	GasAdjustedAmountIn  string                 `protobuf:"bytes,11,opt,name=gasAdjustedAmountIn,proto3" json:"gasAdjustedAmountIn,omitempty"`
	GasAdjustedAmountOut string                 `protobuf:"bytes,12,opt,name=gasAdjustedAmountOut,proto3" json:"gasAdjustedAmountOut,omitempty"`
	RankingMetric        string                 `protobuf:"bytes,13,opt,name=rankingMetric,proto3" json:"rankingMetric,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RouteView) Reset() {
	*x = RouteView{}
	mi := &file_rpc_proto_executor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteView) ProtoMessage() {}

func (x *RouteView) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_executor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteView.ProtoReflect.Descriptor instead.
func (*RouteView) Descriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{12}
}

func (x *RouteView) GetPathTokens() []string {
	if x != nil {
		return x.PathTokens
	}
	return nil
}

func (x *RouteView) GetExecutionPath() []string {
	if x != nil {
		return x.ExecutionPath
	}
	return nil
}

func (x *RouteView) GetHops() uint32 {
	if x != nil {
		return x.Hops
	}
	return 0
}

func (x *RouteView) GetIsDirect() bool {
	if x != nil {
		return x.IsDirect
	}
	return false
}

func (x *RouteView) GetIsMultiHop() bool {
	if x != nil {
		return x.IsMultiHop
	}
	return false
}

func (x *RouteView) GetAmountIn() string {
	if x != nil {
		return x.AmountIn
	}
	return ""
}

func (x *RouteView) GetAmountOut() string {
	if x != nil {
		return x.AmountOut
	}
	return ""
}

func (x *RouteView) GetGasEstimate() uint64 {
	if x != nil {
		return x.GasEstimate
	}
	return 0
}

func (x *RouteView) GetGasCostInInputToken() string {
	if x != nil {
		return x.GasCostInInputToken
	}
	return ""
}

func (x *RouteView) GetGasCostInOutputToken() string {
	if x != nil {
		return x.GasCostInOutputToken
	}
	return ""
}

func (x *RouteView) GetGasAdjustedAmountIn() string {
	if x != nil {
		return x.GasAdjustedAmountIn
	}
	return ""
}

func (x *RouteView) GetGasAdjustedAmountOut() string {
	if x != nil {
		return x.GasAdjustedAmountOut
	}
	return ""
}

func (x *RouteView) GetRankingMetric() string {
	if x != nil {
		return x.RankingMetric
	}
	return ""
}

type RouteExecution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouterPath    []string               `protobuf:"bytes,1,rep,name=routerPath,proto3" json:"routerPath,omitempty"`
	IsMultiHop    bool                   `protobuf:"varint,2,opt,name=isMultiHop,proto3" json:"isMultiHop,omitempty"`
	Strategy      string                 `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteExecution) Reset() {
	*x = RouteExecution{}
	mi := &file_rpc_proto_executor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteExecution) ProtoMessage() {}

func (x *RouteExecution) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_executor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteExecution.ProtoReflect.Descriptor instead.
func (*RouteExecution) Descriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{13}
}

func (x *RouteExecution) GetRouterPath() []string {
	if x != nil {
		return x.RouterPath
	}
	return nil
}

func (x *RouteExecution) GetIsMultiHop() bool {
	if x != nil {
		return x.IsMultiHop
	}
	return false
}

func (x *RouteExecution) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

type GetBestRouteResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Notice                 *ResponseNotice        `protobuf:"bytes,1,opt,name=notice,proto3" json:"notice,omitempty"`
	SelectedRoute          *RouteView             `protobuf:"bytes,2,opt,name=selectedRoute,proto3" json:"selectedRoute,omitempty"`
	AlternativeRoutes      []*RouteView           `protobuf:"bytes,3,rep,name=alternativeRoutes,proto3" json:"alternativeRoutes,omitempty"`
	Execution              *RouteExecution        `protobuf:"bytes,4,opt,name=execution,proto3" json:"execution,omitempty"`
	SelectionReason        string                 `protobuf:"bytes,5,opt,name=selectionReason,proto3" json:"selectionReason,omitempty"`
	UsedGasAdjustedRanking bool                   `protobuf:"varint,6,opt,name=usedGasAdjustedRanking,proto3" json:"usedGasAdjustedRanking,omitempty"`
	Quote                  *RouteQuote            `protobuf:"bytes,7,opt,name=quote,proto3" json:"quote,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetBestRouteResponse) Reset() {
	*x = GetBestRouteResponse{}
	mi := &file_rpc_proto_executor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBestRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBestRouteResponse) ProtoMessage() {}

func (x *GetBestRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_executor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBestRouteResponse.ProtoReflect.Descriptor instead.
func (*GetBestRouteResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_executor_proto_rawDescGZIP(), []int{14}
}

func (x *GetBestRouteResponse) GetNotice() *ResponseNotice {
	if x != nil {
		return x.Notice
	}
	return nil
}

func (x *GetBestRouteResponse) GetSelectedRoute() *RouteView {
	if x != nil {
		return x.SelectedRoute
	}
	return nil
}

func (x *GetBestRouteResponse) GetAlternativeRoutes() []*RouteView {
	if x != nil {
		return x.AlternativeRoutes
	}
	return nil
}

func (x *GetBestRouteResponse) GetExecution() *RouteExecution {
	if x != nil {
		return x.Execution
	}
	return nil
}

func (x *GetBestRouteResponse) GetSelectionReason() string {
	if x != nil {
		return x.SelectionReason
	}
	return ""
}

func (x *GetBestRouteResponse) GetUsedGasAdjustedRanking() bool {
	if x != nil {
		return x.UsedGasAdjustedRanking
	}
	return false
}

func (x *GetBestRouteResponse) GetQuote() *RouteQuote {
	if x != nil {
		return x.Quote
	}
	return nil
}

var File_rpc_proto_executor_proto protoreflect.FileDescriptor

const file_rpc_proto_executor_proto_rawDesc = "" +
	"\n" +
	"\x18rpc/proto/executor.proto\x12\bexecutor\"\x82\x01\n" +
	"\x0eResponseNotice\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x12\n" +
	"\x04hint\x18\x04 \x01(\tR\x04hint\x12\x14\n" +
	"\x05stage\x18\x05 \x01(\tR\x05stage\"\xf2\x03\n" +
	"\x12CreateOrderRequest\x12\x18\n" +
	"\achainId\x18\x01 \x01(\x03R\achainId\x12,\n" +
	"\x11settlementAddress\x18\x02 \x01(\tR\x11settlementAddress\x12\x1c\n" +
	"\torderHash\x18\x03 \x01(\tR\torderHash\x12\x14\n" +
	"\x05maker\x18\x04 \x01(\tR\x05maker\x12\x1e\n" +
	"\n" +
	"inputToken\x18\x05 \x01(\tR\n" +
	"inputToken\x12 \n" +
	"\voutputToken\x18\x06 \x01(\tR\voutputToken\x12\x1a\n" +
	"\bamountIn\x18\a \x01(\tR\bamountIn\x12\"\n" +
	"\fminAmountOut\x18\b \x01(\tR\fminAmountOut\x12(\n" +
	"\x0ftriggerPriceX18\x18\t \x01(\tR\x0ftriggerPriceX18\x12\x16\n" +
	"\x06expiry\x18\n" +
	" \x01(\tR\x06expiry\x12\x14\n" +
	"\x05nonce\x18\v \x01(\tR\x05nonce\x12\x1c\n" +
	"\trecipient\x18\f \x01(\tR\trecipient\x12\x1c\n" +
	"\tsignature\x18\r \x01(\tR\tsignature\x12\x16\n" +
	"\x06source\x18\x0e \x01(\tR\x06source\x122\n" +
	"\x14maxExecutorRewardBps\x18\x0f \x01(\tR\x14maxExecutorRewardBps\"y\n" +
	"\x13CreateOrderResponse\x120\n" +
	"\x05order\x18\x01 \x01(\v2\x1a.executor.GetOrderResponseR\x05order\x120\n" +
	"\x06notice\x18\x02 \x01(\v2\x18.executor.ResponseNoticeR\x06notice\"\xa5\x01\n" +
	"\x0fCancelOrderItem\x12\x18\n" +
	"\achainId\x18\x01 \x01(\x03R\achainId\x12,\n" +
	"\x11settlementAddress\x18\x02 \x01(\tR\x11settlementAddress\x12\x1c\n" +
	"\torderHash\x18\x03 \x01(\tR\torderHash\x12\x14\n" +
	"\x05maker\x18\x04 \x01(\tR\x05maker\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"l\n" +
	"\x13CancelOrdersRequest\x121\n" +
	"\x06orders\x18\x01 \x03(\v2\x19.executor.CancelOrderItemR\x06orders\x12\"\n" +
	"\fcancelTxHash\x18\x02 \x01(\tR\fcancelTxHash\"\xb8\x02\n" +
	"\x12CancelOrdersResult\x12\x18\n" +
	"\achainId\x18\x01 \x01(\x03R\achainId\x12,\n" +
	"\x11settlementAddress\x18\x02 \x01(\tR\x11settlementAddress\x12\x1c\n" +
	"\torderHash\x18\x03 \x01(\tR\torderHash\x12\x1c\n" +
	"\tcancelled\x18\x04 \x01(\bR\tcancelled\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x12\n" +
	"\x04code\x18\x06 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12\x12\n" +
	"\x04hint\x18\b \x01(\tR\x04hint\x12\x14\n" +
	"\x05stage\x18\t \x01(\tR\x05stage\x120\n" +
	"\x05order\x18\n" +
	" \x01(\v2\x1a.executor.GetOrderResponseR\x05order\"\xbe\x01\n" +
	"\x14CancelOrdersResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\rR\x05total\x12&\n" +
	"\x0ecancelledCount\x18\x02 \x01(\rR\x0ecancelledCount\x126\n" +
	"\aresults\x18\x03 \x03(\v2\x1c.executor.CancelOrdersResultR\aresults\x120\n" +
	"\x06notice\x18\x04 \x01(\v2\x18.executor.ResponseNoticeR\x06notice\"w\n" +
	"\x0fGetOrderRequest\x12\x18\n" +
	"\achainId\x18\x01 \x01(\x03R\achainId\x12,\n" +
	"\x11settlementAddress\x18\x02 \x01(\tR\x11settlementAddress\x12\x1c\n" +
	"\torderHash\x18\x03 \x01(\tR\torderHash\"\x8a\n" +
	"\n" +
	"\x10GetOrderResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\achainId\x18\x02 \x01(\x03R\achainId\x12,\n" +
	"\x11settlementAddress\x18\x03 \x01(\tR\x11settlementAddress\x12\x1c\n" +
	"\torderHash\x18\x04 \x01(\tR\torderHash\x12\x14\n" +
	"\x05maker\x18\x05 \x01(\tR\x05maker\x12\x1e\n" +
	"\n" +
	"inputToken\x18\x06 \x01(\tR\n" +
	"inputToken\x12 \n" +
	"\voutputToken\x18\a \x01(\tR\voutputToken\x12\x1a\n" +
	"\bamountIn\x18\b \x01(\tR\bamountIn\x12\"\n" +
	"\fminAmountOut\x18\t \x01(\tR\fminAmountOut\x12(\n" +
	"\x0ftriggerPriceX18\x18\n" +
	" \x01(\tR\x0ftriggerPriceX18\x12\x16\n" +
	"\x06expiry\x18\v \x01(\tR\x06expiry\x12\x14\n" +
	"\x05nonce\x18\f \x01(\tR\x05nonce\x12\x1c\n" +
	"\trecipient\x18\r \x01(\tR\trecipient\x12\x16\n" +
	"\x06source\x18\x0e \x01(\tR\x06source\x12\x16\n" +
	"\x06status\x18\x0f \x01(\tR\x06status\x12\"\n" +
	"\fstatusReason\x18\x10 \x01(\tR\fstatusReason\x12(\n" +
	"\x0fsubmittedTxHash\x18\x11 \x01(\tR\x0fsubmittedTxHash\x12&\n" +
	"\x0eexecutedTxHash\x18\x12 \x01(\tR\x0eexecutedTxHash\x12(\n" +
	"\x0fcancelledTxHash\x18\x13 \x01(\tR\x0fcancelledTxHash\x12*\n" +
	"\x10lastCheckedBlock\x18\x14 \x01(\x03R\x10lastCheckedBlock\x12\x1c\n" +
	"\tcreatedAt\x18\x15 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x16 \x01(\tR\tupdatedAt\x120\n" +
	"\x06notice\x18\x17 \x01(\v2\x18.executor.ResponseNoticeR\x06notice\x122\n" +
	"\x14maxExecutorRewardBps\x18\x18 \x01(\tR\x14maxExecutorRewardBps\x12*\n" +
	"\x10executorFeeToken\x18\x19 \x01(\tR\x10executorFeeToken\x12*\n" +
	"\x10estimatedGasUsed\x18\x1a \x01(\tR\x10estimatedGasUsed\x12(\n" +
	"\x0fgasPriceAtQuote\x18\x1b \x01(\tR\x0fgasPriceAtQuote\x12$\n" +
	"\rrewardQuoteAt\x18\x1c \x01(\tR\rrewardQuoteAt\x12>\n" +
	"\x1alastRequiredExecutorReward\x18\x1d \x01(\tR\x1alastRequiredExecutorReward\x12,\n" +
	"\x11lastRewardCheckAt\x18\x1e \x01(\tR\x11lastRewardCheckAt\x122\n" +
	"\x14lastExecutionCheckAt\x18\x1f \x01(\tR\x14lastExecutionCheckAt\x12(\n" +
	"\x0flastBlockReason\x18  \x01(\tR\x0flastBlockReason\x12*\n" +
	"\x10settledAmountOut\x18! \x01(\tR\x10settledAmountOut\x124\n" +
	"\x15settledExecutorReward\x18\" \x01(\tR\x15settledExecutorReward\"\xcf\x01\n" +
	"\x13GetBestRouteRequest\x12\x18\n" +
	"\achainId\x18\x01 \x01(\x03R\achainId\x12\x18\n" +
	"\atokenIn\x18\x02 \x01(\tR\atokenIn\x12\x1a\n" +
	"\btokenOut\x18\x03 \x01(\tR\btokenOut\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x18\n" +
	"\amaxHops\x18\x05 \x01(\rR\amaxHops\x126\n" +
	"\tquoteType\x18\x06 \x01(\x0e2\x18.executor.RouteQuoteTypeR\tquoteType\"\xdf\x02\n" +
	"\tRoutePath\x12\x16\n" +
	"\x06tokens\x18\x01 \x03(\tR\x06tokens\x12\x12\n" +
	"\x04hops\x18\x02 \x01(\rR\x04hops\x12\x1a\n" +
	"\bamountIn\x18\x03 \x01(\tR\bamountIn\x12\x1c\n" +
	"\tamountOut\x18\x04 \x01(\tR\tamountOut\x12 \n" +
	"\vgasEstimate\x18\x05 \x01(\x04R\vgasEstimate\x120\n" +
	"\x13gasCostInInputToken\x18\x06 \x01(\tR\x13gasCostInInputToken\x122\n" +
	"\x14gasCostInOutputToken\x18\a \x01(\tR\x14gasCostInOutputToken\x120\n" +
	"\x13gasAdjustedAmountIn\x18\b \x01(\tR\x13gasAdjustedAmountIn\x122\n" +
	"\x14gasAdjustedAmountOut\x18\t \x01(\tR\x14gasAdjustedAmountOut\"~\n" +
	"\n" +
	"RouteQuote\x126\n" +
	"\tquoteType\x18\x01 \x01(\x0e2\x18.executor.RouteQuoteTypeR\tquoteType\x12\x1a\n" +
	"\bamountIn\x18\x02 \x01(\tR\bamountIn\x12\x1c\n" +
	"\tamountOut\x18\x03 \x01(\tR\tamountOut\"\xef\x03\n" +
	"\tRouteView\x12\x1e\n" +
	"\n" +
	"pathTokens\x18\x01 \x03(\tR\n" +
	"pathTokens\x12$\n" +
	"\rexecutionPath\x18\x02 \x03(\tR\rexecutionPath\x12\x12\n" +
	"\x04hops\x18\x03 \x01(\rR\x04hops\x12\x1a\n" +
	"\bisDirect\x18\x04 \x01(\bR\bisDirect\x12\x1e\n" +
	"\n" +
	"isMultiHop\x18\x05 \x01(\bR\n" +
	"isMultiHop\x12\x1a\n" +
	"\bamountIn\x18\x06 \x01(\tR\bamountIn\x12\x1c\n" +
	"\tamountOut\x18\a \x01(\tR\tamountOut\x12 \n" +
	"\vgasEstimate\x18\b \x01(\x04R\vgasEstimate\x120\n" +
	"\x13gasCostInInputToken\x18\t \x01(\tR\x13gasCostInInputToken\x122\n" +
	"\x14gasCostInOutputToken\x18\n" +
	" \x01(\tR\x14gasCostInOutputToken\x120\n" +
	"\x13gasAdjustedAmountIn\x18\v \x01(\tR\x13gasAdjustedAmountIn\x122\n" +
	"\x14gasAdjustedAmountOut\x18\f \x01(\tR\x14gasAdjustedAmountOut\x12$\n" +
	"\rrankingMetric\x18\r \x01(\tR\rrankingMetric\"l\n" +
	"\x0eRouteExecution\x12\x1e\n" +
	"\n" +
	"routerPath\x18\x01 \x03(\tR\n" +
	"routerPath\x12\x1e\n" +
	"\n" +
	"isMultiHop\x18\x02 \x01(\bR\n" +
	"isMultiHop\x12\x1a\n" +
	"\bstrategy\x18\x03 \x01(\tR\bstrategy\"\x8c\x03\n" +
	"\x14GetBestRouteResponse\x120\n" +
	"\x06notice\x18\x01 \x01(\v2\x18.executor.ResponseNoticeR\x06notice\x129\n" +
	"\rselectedRoute\x18\x02 \x01(\v2\x13.executor.RouteViewR\rselectedRoute\x12A\n" +
	"\x11alternativeRoutes\x18\x03 \x03(\v2\x13.executor.RouteViewR\x11alternativeRoutes\x126\n" +
	"\texecution\x18\x04 \x01(\v2\x18.executor.RouteExecutionR\texecution\x12(\n" +
	"\x0fselectionReason\x18\x05 \x01(\tR\x0fselectionReason\x126\n" +
	"\x16usedGasAdjustedRanking\x18\x06 \x01(\bR\x16usedGasAdjustedRanking\x12*\n" +
	"\x05quote\x18\a \x01(\v2\x14.executor.RouteQuoteR\x05quote*w\n" +
	"\x0eRouteQuoteType\x12 \n" +
	"\x1cROUTE_QUOTE_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cROUTE_QUOTE_TYPE_EXACT_INPUT\x10\x01\x12!\n" +
	"\x1dROUTE_QUOTE_TYPE_EXACT_OUTPUT\x10\x022\xb7\x02\n" +
	"\bExecutor\x12J\n" +
	"\vCreateOrder\x12\x1c.executor.CreateOrderRequest\x1a\x1d.executor.CreateOrderResponse\x12M\n" +
	"\fCancelOrders\x12\x1d.executor.CancelOrdersRequest\x1a\x1e.executor.CancelOrdersResponse\x12A\n" +
	"\bGetOrder\x12\x19.executor.GetOrderRequest\x1a\x1a.executor.GetOrderResponse\x12M\n" +
	"\fGetBestRoute\x12\x1d.executor.GetBestRouteRequest\x1a\x1e.executor.GetBestRouteResponseB\fZ\n" +
	"./executorb\x06proto3"

var (
	file_rpc_proto_executor_proto_rawDescOnce sync.Once
	file_rpc_proto_executor_proto_rawDescData []byte
)

func file_rpc_proto_executor_proto_rawDescGZIP() []byte {
	file_rpc_proto_executor_proto_rawDescOnce.Do(func() {
		file_rpc_proto_executor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_proto_executor_proto_rawDesc), len(file_rpc_proto_executor_proto_rawDesc)))
	})
	return file_rpc_proto_executor_proto_rawDescData
}

var file_rpc_proto_executor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_proto_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_rpc_proto_executor_proto_goTypes = []any{
	(RouteQuoteType)(0),          // 0: executor.RouteQuoteType
	(*ResponseNotice)(nil),       // 1: executor.ResponseNotice
	(*CreateOrderRequest)(nil),   // 2: executor.CreateOrderRequest
	(*CreateOrderResponse)(nil),  // 3: executor.CreateOrderResponse
	(*CancelOrderItem)(nil),      // 4: executor.CancelOrderItem
	(*CancelOrdersRequest)(nil),  // 5: executor.CancelOrdersRequest
	(*CancelOrdersResult)(nil),   // 6: executor.CancelOrdersResult
	(*CancelOrdersResponse)(nil), // 7: executor.CancelOrdersResponse
	(*GetOrderRequest)(nil),      // 8: executor.GetOrderRequest
	(*GetOrderResponse)(nil),     // 9: executor.GetOrderResponse
	(*GetBestRouteRequest)(nil),  // 10: executor.GetBestRouteRequest
	(*RoutePath)(nil),            // 11: executor.RoutePath
	(*RouteQuote)(nil),           // 12: executor.RouteQuote
	(*RouteView)(nil),            // 13: executor.RouteView
	(*RouteExecution)(nil),       // 14: executor.RouteExecution
	(*GetBestRouteResponse)(nil), // 15: executor.GetBestRouteResponse
}
var file_rpc_proto_executor_proto_depIdxs = []int32{
	9,  // 0: executor.CreateOrderResponse.order:type_name -> executor.GetOrderResponse
	1,  // 1: executor.CreateOrderResponse.notice:type_name -> executor.ResponseNotice
	4,  // 2: executor.CancelOrdersRequest.orders:type_name -> executor.CancelOrderItem
	9,  // 3: executor.CancelOrdersResult.order:type_name -> executor.GetOrderResponse
	6,  // 4: executor.CancelOrdersResponse.results:type_name -> executor.CancelOrdersResult
	1,  // 5: executor.CancelOrdersResponse.notice:type_name -> executor.ResponseNotice
	1,  // 6: executor.GetOrderResponse.notice:type_name -> executor.ResponseNotice
	0,  // 7: executor.GetBestRouteRequest.quoteType:type_name -> executor.RouteQuoteType
	0,  // 8: executor.RouteQuote.quoteType:type_name -> executor.RouteQuoteType
	1,  // 9: executor.GetBestRouteResponse.notice:type_name -> executor.ResponseNotice
	13, // 10: executor.GetBestRouteResponse.selectedRoute:type_name -> executor.RouteView
	13, // 11: executor.GetBestRouteResponse.alternativeRoutes:type_name -> executor.RouteView
	14, // 12: executor.GetBestRouteResponse.execution:type_name -> executor.RouteExecution
	12, // 13: executor.GetBestRouteResponse.quote:type_name -> executor.RouteQuote
	2,  // 14: executor.Executor.CreateOrder:input_type -> executor.CreateOrderRequest
	5,  // 15: executor.Executor.CancelOrders:input_type -> executor.CancelOrdersRequest
	8,  // 16: executor.Executor.GetOrder:input_type -> executor.GetOrderRequest
	10, // 17: executor.Executor.GetBestRoute:input_type -> executor.GetBestRouteRequest
	3,  // 18: executor.Executor.CreateOrder:output_type -> executor.CreateOrderResponse
	7,  // 19: executor.Executor.CancelOrders:output_type -> executor.CancelOrdersResponse
	9,  // 20: executor.Executor.GetOrder:output_type -> executor.GetOrderResponse
	15, // 21: executor.Executor.GetBestRoute:output_type -> executor.GetBestRouteResponse
	18, // [18:22] is the sub-list for method output_type
	14, // [14:18] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_rpc_proto_executor_proto_init() }
func file_rpc_proto_executor_proto_init() {
	if File_rpc_proto_executor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proto_executor_proto_rawDesc), len(file_rpc_proto_executor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proto_executor_proto_goTypes,
		DependencyIndexes: file_rpc_proto_executor_proto_depIdxs,
		EnumInfos:         file_rpc_proto_executor_proto_enumTypes,
		MessageInfos:      file_rpc_proto_executor_proto_msgTypes,
	}.Build()
	File_rpc_proto_executor_proto = out.File
	file_rpc_proto_executor_proto_goTypes = nil
	file_rpc_proto_executor_proto_depIdxs = nil
}
