// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: proto/executor.proto

package executor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseNotice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Hint          string                 `protobuf:"bytes,4,opt,name=hint,proto3" json:"hint,omitempty"`
	Stage         string                 `protobuf:"bytes,5,opt,name=stage,proto3" json:"stage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseNotice) Reset() {
	*x = ResponseNotice{}
	mi := &file_proto_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseNotice) ProtoMessage() {}

func (x *ResponseNotice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseNotice.ProtoReflect.Descriptor instead.
func (*ResponseNotice) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseNotice) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResponseNotice) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseNotice) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseNotice) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

func (x *ResponseNotice) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

type CreateOrderRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ChainId              int64                  `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	SettlementAddress    string                 `protobuf:"bytes,2,opt,name=settlementAddress,proto3" json:"settlementAddress,omitempty"`
	OrderHash            string                 `protobuf:"bytes,3,opt,name=orderHash,proto3" json:"orderHash,omitempty"`
	Maker                string                 `protobuf:"bytes,4,opt,name=maker,proto3" json:"maker,omitempty"`
	InputToken           string                 `protobuf:"bytes,5,opt,name=inputToken,proto3" json:"inputToken,omitempty"`
	OutputToken          string                 `protobuf:"bytes,6,opt,name=outputToken,proto3" json:"outputToken,omitempty"`
	AmountIn             string                 `protobuf:"bytes,7,opt,name=amountIn,proto3" json:"amountIn,omitempty"`
	MinAmountOut         string                 `protobuf:"bytes,8,opt,name=minAmountOut,proto3" json:"minAmountOut,omitempty"`
	TriggerPriceX18      string                 `protobuf:"bytes,9,opt,name=triggerPriceX18,proto3" json:"triggerPriceX18,omitempty"`
	Expiry               string                 `protobuf:"bytes,10,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Nonce                string                 `protobuf:"bytes,11,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Recipient            string                 `protobuf:"bytes,12,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Signature            string                 `protobuf:"bytes,13,opt,name=signature,proto3" json:"signature,omitempty"`
	Source               string                 `protobuf:"bytes,14,opt,name=source,proto3" json:"source,omitempty"`
	MaxExecutorRewardBps string                 `protobuf:"bytes,15,opt,name=maxExecutorRewardBps,proto3" json:"maxExecutorRewardBps,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_proto_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *CreateOrderRequest) GetSettlementAddress() string {
	if x != nil {
		return x.SettlementAddress
	}
	return ""
}

func (x *CreateOrderRequest) GetOrderHash() string {
	if x != nil {
		return x.OrderHash
	}
	return ""
}

func (x *CreateOrderRequest) GetMaker() string {
	if x != nil {
		return x.Maker
	}
	return ""
}

func (x *CreateOrderRequest) GetInputToken() string {
	if x != nil {
		return x.InputToken
	}
	return ""
}

func (x *CreateOrderRequest) GetOutputToken() string {
	if x != nil {
		return x.OutputToken
	}
	return ""
}

func (x *CreateOrderRequest) GetAmountIn() string {
	if x != nil {
		return x.AmountIn
	}
	return ""
}

func (x *CreateOrderRequest) GetMinAmountOut() string {
	if x != nil {
		return x.MinAmountOut
	}
	return ""
}

func (x *CreateOrderRequest) GetTriggerPriceX18() string {
	if x != nil {
		return x.TriggerPriceX18
	}
	return ""
}

func (x *CreateOrderRequest) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

func (x *CreateOrderRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *CreateOrderRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *CreateOrderRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *CreateOrderRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CreateOrderRequest) GetMaxExecutorRewardBps() string {
	if x != nil {
		return x.MaxExecutorRewardBps
	}
	return ""
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *GetOrderResponse      `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Notice        *ResponseNotice        `protobuf:"bytes,2,opt,name=notice,proto3" json:"notice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_proto_executor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderResponse) GetOrder() *GetOrderResponse {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *CreateOrderResponse) GetNotice() *ResponseNotice {
	if x != nil {
		return x.Notice
	}
	return nil
}

type CancelOrderItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChainId           int64                  `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	SettlementAddress string                 `protobuf:"bytes,2,opt,name=settlementAddress,proto3" json:"settlementAddress,omitempty"`
	OrderHash         string                 `protobuf:"bytes,3,opt,name=orderHash,proto3" json:"orderHash,omitempty"`
	Maker             string                 `protobuf:"bytes,4,opt,name=maker,proto3" json:"maker,omitempty"`
	Reason            string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CancelOrderItem) Reset() {
	*x = CancelOrderItem{}
	mi := &file_proto_executor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderItem) ProtoMessage() {}

func (x *CancelOrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderItem.ProtoReflect.Descriptor instead.
func (*CancelOrderItem) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{3}
}

func (x *CancelOrderItem) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *CancelOrderItem) GetSettlementAddress() string {
	if x != nil {
		return x.SettlementAddress
	}
	return ""
}

func (x *CancelOrderItem) GetOrderHash() string {
	if x != nil {
		return x.OrderHash
	}
	return ""
}

func (x *CancelOrderItem) GetMaker() string {
	if x != nil {
		return x.Maker
	}
	return ""
}

func (x *CancelOrderItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*CancelOrderItem     `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	CancelTxHash  string                 `protobuf:"bytes,2,opt,name=cancelTxHash,proto3" json:"cancelTxHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrdersRequest) Reset() {
	*x = CancelOrdersRequest{}
	mi := &file_proto_executor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrdersRequest) ProtoMessage() {}

func (x *CancelOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrdersRequest.ProtoReflect.Descriptor instead.
func (*CancelOrdersRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{4}
}

func (x *CancelOrdersRequest) GetOrders() []*CancelOrderItem {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *CancelOrdersRequest) GetCancelTxHash() string {
	if x != nil {
		return x.CancelTxHash
	}
	return ""
}

type CancelOrdersResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChainId           int64                  `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	SettlementAddress string                 `protobuf:"bytes,2,opt,name=settlementAddress,proto3" json:"settlementAddress,omitempty"`
	OrderHash         string                 `protobuf:"bytes,3,opt,name=orderHash,proto3" json:"orderHash,omitempty"`
	Cancelled         bool                   `protobuf:"varint,4,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	Error             string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Code              string                 `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	Message           string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	Hint              string                 `protobuf:"bytes,8,opt,name=hint,proto3" json:"hint,omitempty"`
	Stage             string                 `protobuf:"bytes,9,opt,name=stage,proto3" json:"stage,omitempty"`
	Order             *GetOrderResponse      `protobuf:"bytes,10,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CancelOrdersResult) Reset() {
	*x = CancelOrdersResult{}
	mi := &file_proto_executor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrdersResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrdersResult) ProtoMessage() {}

func (x *CancelOrdersResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrdersResult.ProtoReflect.Descriptor instead.
func (*CancelOrdersResult) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{5}
}

func (x *CancelOrdersResult) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *CancelOrdersResult) GetSettlementAddress() string {
	if x != nil {
		return x.SettlementAddress
	}
	return ""
}

func (x *CancelOrdersResult) GetOrderHash() string {
	if x != nil {
		return x.OrderHash
	}
	return ""
}

func (x *CancelOrdersResult) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

func (x *CancelOrdersResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CancelOrdersResult) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CancelOrdersResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CancelOrdersResult) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

func (x *CancelOrdersResult) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *CancelOrdersResult) GetOrder() *GetOrderResponse {
	if x != nil {
		return x.Order
	}
	return nil
}

type CancelOrdersResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Total          uint32                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	CancelledCount uint32                 `protobuf:"varint,2,opt,name=cancelledCount,proto3" json:"cancelledCount,omitempty"`
	Results        []*CancelOrdersResult  `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	Notice         *ResponseNotice        `protobuf:"bytes,4,opt,name=notice,proto3" json:"notice,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelOrdersResponse) Reset() {
	*x = CancelOrdersResponse{}
	mi := &file_proto_executor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrdersResponse) ProtoMessage() {}

func (x *CancelOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrdersResponse.ProtoReflect.Descriptor instead.
func (*CancelOrdersResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{6}
}

func (x *CancelOrdersResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CancelOrdersResponse) GetCancelledCount() uint32 {
	if x != nil {
		return x.CancelledCount
	}
	return 0
}

func (x *CancelOrdersResponse) GetResults() []*CancelOrdersResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *CancelOrdersResponse) GetNotice() *ResponseNotice {
	if x != nil {
		return x.Notice
	}
	return nil
}

type GetOrderRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChainId           int64                  `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	SettlementAddress string                 `protobuf:"bytes,2,opt,name=settlementAddress,proto3" json:"settlementAddress,omitempty"`
	OrderHash         string                 `protobuf:"bytes,3,opt,name=orderHash,proto3" json:"orderHash,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_proto_executor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrderRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetOrderRequest) GetSettlementAddress() string {
	if x != nil {
		return x.SettlementAddress
	}
	return ""
}

func (x *GetOrderRequest) GetOrderHash() string {
	if x != nil {
		return x.OrderHash
	}
	return ""
}

type GetOrderResponse struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Id                         uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ChainId                    int64                  `protobuf:"varint,2,opt,name=chainId,proto3" json:"chainId,omitempty"`
	SettlementAddress          string                 `protobuf:"bytes,3,opt,name=settlementAddress,proto3" json:"settlementAddress,omitempty"`
	OrderHash                  string                 `protobuf:"bytes,4,opt,name=orderHash,proto3" json:"orderHash,omitempty"`
	Maker                      string                 `protobuf:"bytes,5,opt,name=maker,proto3" json:"maker,omitempty"`
	InputToken                 string                 `protobuf:"bytes,6,opt,name=inputToken,proto3" json:"inputToken,omitempty"`
	OutputToken                string                 `protobuf:"bytes,7,opt,name=outputToken,proto3" json:"outputToken,omitempty"`
	AmountIn                   string                 `protobuf:"bytes,8,opt,name=amountIn,proto3" json:"amountIn,omitempty"`
	MinAmountOut               string                 `protobuf:"bytes,9,opt,name=minAmountOut,proto3" json:"minAmountOut,omitempty"`
	TriggerPriceX18            string                 `protobuf:"bytes,10,opt,name=triggerPriceX18,proto3" json:"triggerPriceX18,omitempty"`
	Expiry                     string                 `protobuf:"bytes,11,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Nonce                      string                 `protobuf:"bytes,12,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Recipient                  string                 `protobuf:"bytes,13,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Source                     string                 `protobuf:"bytes,14,opt,name=source,proto3" json:"source,omitempty"`
	Status                     string                 `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty"`
	StatusReason               string                 `protobuf:"bytes,16,opt,name=statusReason,proto3" json:"statusReason,omitempty"`
	SubmittedTxHash            string                 `protobuf:"bytes,17,opt,name=submittedTxHash,proto3" json:"submittedTxHash,omitempty"`
	ExecutedTxHash             string                 `protobuf:"bytes,18,opt,name=executedTxHash,proto3" json:"executedTxHash,omitempty"`
	CancelledTxHash            string                 `protobuf:"bytes,19,opt,name=cancelledTxHash,proto3" json:"cancelledTxHash,omitempty"`
	LastCheckedBlock           int64                  `protobuf:"varint,20,opt,name=lastCheckedBlock,proto3" json:"lastCheckedBlock,omitempty"`
	CreatedAt                  string                 `protobuf:"bytes,21,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt                  string                 `protobuf:"bytes,22,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Notice                     *ResponseNotice        `protobuf:"bytes,23,opt,name=notice,proto3" json:"notice,omitempty"`
	MaxExecutorRewardBps       string                 `protobuf:"bytes,24,opt,name=maxExecutorRewardBps,proto3" json:"maxExecutorRewardBps,omitempty"`
	ExecutorFeeToken           string                 `protobuf:"bytes,25,opt,name=executorFeeToken,proto3" json:"executorFeeToken,omitempty"`
	EstimatedGasUsed           string                 `protobuf:"bytes,26,opt,name=estimatedGasUsed,proto3" json:"estimatedGasUsed,omitempty"`
	GasPriceAtQuote            string                 `protobuf:"bytes,27,opt,name=gasPriceAtQuote,proto3" json:"gasPriceAtQuote,omitempty"`
	RewardQuoteAt              string                 `protobuf:"bytes,28,opt,name=rewardQuoteAt,proto3" json:"rewardQuoteAt,omitempty"`
	LastRequiredExecutorReward string                 `protobuf:"bytes,29,opt,name=lastRequiredExecutorReward,proto3" json:"lastRequiredExecutorReward,omitempty"`
	LastRewardCheckAt          string                 `protobuf:"bytes,30,opt,name=lastRewardCheckAt,proto3" json:"lastRewardCheckAt,omitempty"`
	LastExecutionCheckAt       string                 `protobuf:"bytes,31,opt,name=lastExecutionCheckAt,proto3" json:"lastExecutionCheckAt,omitempty"`
	LastBlockReason            string                 `protobuf:"bytes,32,opt,name=lastBlockReason,proto3" json:"lastBlockReason,omitempty"`
	SettledAmountOut           string                 `protobuf:"bytes,33,opt,name=settledAmountOut,proto3" json:"settledAmountOut,omitempty"`
	SettledExecutorReward      string                 `protobuf:"bytes,34,opt,name=settledExecutorReward,proto3" json:"settledExecutorReward,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_proto_executor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrderResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetOrderResponse) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetOrderResponse) GetSettlementAddress() string {
	if x != nil {
		return x.SettlementAddress
	}
	return ""
}

func (x *GetOrderResponse) GetOrderHash() string {
	if x != nil {
		return x.OrderHash
	}
	return ""
}

func (x *GetOrderResponse) GetMaker() string {
	if x != nil {
		return x.Maker
	}
	return ""
}

func (x *GetOrderResponse) GetInputToken() string {
	if x != nil {
		return x.InputToken
	}
	return ""
}

func (x *GetOrderResponse) GetOutputToken() string {
	if x != nil {
		return x.OutputToken
	}
	return ""
}

func (x *GetOrderResponse) GetAmountIn() string {
	if x != nil {
		return x.AmountIn
	}
	return ""
}

func (x *GetOrderResponse) GetMinAmountOut() string {
	if x != nil {
		return x.MinAmountOut
	}
	return ""
}

func (x *GetOrderResponse) GetTriggerPriceX18() string {
	if x != nil {
		return x.TriggerPriceX18
	}
	return ""
}

func (x *GetOrderResponse) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

func (x *GetOrderResponse) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *GetOrderResponse) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *GetOrderResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GetOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetOrderResponse) GetStatusReason() string {
	if x != nil {
		return x.StatusReason
	}
	return ""
}

func (x *GetOrderResponse) GetSubmittedTxHash() string {
	if x != nil {
		return x.SubmittedTxHash
	}
	return ""
}

func (x *GetOrderResponse) GetExecutedTxHash() string {
	if x != nil {
		return x.ExecutedTxHash
	}
	return ""
}

func (x *GetOrderResponse) GetCancelledTxHash() string {
	if x != nil {
		return x.CancelledTxHash
	}
	return ""
}

func (x *GetOrderResponse) GetLastCheckedBlock() int64 {
	if x != nil {
		return x.LastCheckedBlock
	}
	return 0
}

func (x *GetOrderResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetOrderResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GetOrderResponse) GetNotice() *ResponseNotice {
	if x != nil {
		return x.Notice
	}
	return nil
}

func (x *GetOrderResponse) GetMaxExecutorRewardBps() string {
	if x != nil {
		return x.MaxExecutorRewardBps
	}
	return ""
}

func (x *GetOrderResponse) GetExecutorFeeToken() string {
	if x != nil {
		return x.ExecutorFeeToken
	}
	return ""
}

func (x *GetOrderResponse) GetEstimatedGasUsed() string {
	if x != nil {
		return x.EstimatedGasUsed
	}
	return ""
}

func (x *GetOrderResponse) GetGasPriceAtQuote() string {
	if x != nil {
		return x.GasPriceAtQuote
	}
	return ""
}

func (x *GetOrderResponse) GetRewardQuoteAt() string {
	if x != nil {
		return x.RewardQuoteAt
	}
	return ""
}

func (x *GetOrderResponse) GetLastRequiredExecutorReward() string {
	if x != nil {
		return x.LastRequiredExecutorReward
	}
	return ""
}

func (x *GetOrderResponse) GetLastRewardCheckAt() string {
	if x != nil {
		return x.LastRewardCheckAt
	}
	return ""
}

func (x *GetOrderResponse) GetLastExecutionCheckAt() string {
	if x != nil {
		return x.LastExecutionCheckAt
	}
	return ""
}

func (x *GetOrderResponse) GetLastBlockReason() string {
	if x != nil {
		return x.LastBlockReason
	}
	return ""
}

func (x *GetOrderResponse) GetSettledAmountOut() string {
	if x != nil {
		return x.SettledAmountOut
	}
	return ""
}

func (x *GetOrderResponse) GetSettledExecutorReward() string {
	if x != nil {
		return x.SettledExecutorReward
	}
	return ""
}

var File_proto_executor_proto protoreflect.FileDescriptor

const file_proto_executor_proto_rawDesc = "" +
	"\n" +
	"\x14proto/executor.proto\x12\bexecutor\"\x82\x01\n" +
	"\x0eResponseNotice\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x12\n" +
	"\x04hint\x18\x04 \x01(\tR\x04hint\x12\x14\n" +
	"\x05stage\x18\x05 \x01(\tR\x05stage\"\xf2\x03\n" +
	"\x12CreateOrderRequest\x12\x18\n" +
	"\achainId\x18\x01 \x01(\x03R\achainId\x12,\n" +
	"\x11settlementAddress\x18\x02 \x01(\tR\x11settlementAddress\x12\x1c\n" +
	"\torderHash\x18\x03 \x01(\tR\torderHash\x12\x14\n" +
	"\x05maker\x18\x04 \x01(\tR\x05maker\x12\x1e\n" +
	"\n" +
	"inputToken\x18\x05 \x01(\tR\n" +
	"inputToken\x12 \n" +
	"\voutputToken\x18\x06 \x01(\tR\voutputToken\x12\x1a\n" +
	"\bamountIn\x18\a \x01(\tR\bamountIn\x12\"\n" +
	"\fminAmountOut\x18\b \x01(\tR\fminAmountOut\x12(\n" +
	"\x0ftriggerPriceX18\x18\t \x01(\tR\x0ftriggerPriceX18\x12\x16\n" +
	"\x06expiry\x18\n" +
	" \x01(\tR\x06expiry\x12\x14\n" +
	"\x05nonce\x18\v \x01(\tR\x05nonce\x12\x1c\n" +
	"\trecipient\x18\f \x01(\tR\trecipient\x12\x1c\n" +
	"\tsignature\x18\r \x01(\tR\tsignature\x12\x16\n" +
	"\x06source\x18\x0e \x01(\tR\x06source\x122\n" +
	"\x14maxExecutorRewardBps\x18\x0f \x01(\tR\x14maxExecutorRewardBps\"y\n" +
	"\x13CreateOrderResponse\x120\n" +
	"\x05order\x18\x01 \x01(\v2\x1a.executor.GetOrderResponseR\x05order\x120\n" +
	"\x06notice\x18\x02 \x01(\v2\x18.executor.ResponseNoticeR\x06notice\"\xa5\x01\n" +
	"\x0fCancelOrderItem\x12\x18\n" +
	"\achainId\x18\x01 \x01(\x03R\achainId\x12,\n" +
	"\x11settlementAddress\x18\x02 \x01(\tR\x11settlementAddress\x12\x1c\n" +
	"\torderHash\x18\x03 \x01(\tR\torderHash\x12\x14\n" +
	"\x05maker\x18\x04 \x01(\tR\x05maker\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"l\n" +
	"\x13CancelOrdersRequest\x121\n" +
	"\x06orders\x18\x01 \x03(\v2\x19.executor.CancelOrderItemR\x06orders\x12\"\n" +
	"\fcancelTxHash\x18\x02 \x01(\tR\fcancelTxHash\"\xb8\x02\n" +
	"\x12CancelOrdersResult\x12\x18\n" +
	"\achainId\x18\x01 \x01(\x03R\achainId\x12,\n" +
	"\x11settlementAddress\x18\x02 \x01(\tR\x11settlementAddress\x12\x1c\n" +
	"\torderHash\x18\x03 \x01(\tR\torderHash\x12\x1c\n" +
	"\tcancelled\x18\x04 \x01(\bR\tcancelled\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x12\n" +
	"\x04code\x18\x06 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12\x12\n" +
	"\x04hint\x18\b \x01(\tR\x04hint\x12\x14\n" +
	"\x05stage\x18\t \x01(\tR\x05stage\x120\n" +
	"\x05order\x18\n" +
	" \x01(\v2\x1a.executor.GetOrderResponseR\x05order\"\xbe\x01\n" +
	"\x14CancelOrdersResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\rR\x05total\x12&\n" +
	"\x0ecancelledCount\x18\x02 \x01(\rR\x0ecancelledCount\x126\n" +
	"\aresults\x18\x03 \x03(\v2\x1c.executor.CancelOrdersResultR\aresults\x120\n" +
	"\x06notice\x18\x04 \x01(\v2\x18.executor.ResponseNoticeR\x06notice\"w\n" +
	"\x0fGetOrderRequest\x12\x18\n" +
	"\achainId\x18\x01 \x01(\x03R\achainId\x12,\n" +
	"\x11settlementAddress\x18\x02 \x01(\tR\x11settlementAddress\x12\x1c\n" +
	"\torderHash\x18\x03 \x01(\tR\torderHash\"\x8a\n" +
	"\n" +
	"\x10GetOrderResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\achainId\x18\x02 \x01(\x03R\achainId\x12,\n" +
	"\x11settlementAddress\x18\x03 \x01(\tR\x11settlementAddress\x12\x1c\n" +
	"\torderHash\x18\x04 \x01(\tR\torderHash\x12\x14\n" +
	"\x05maker\x18\x05 \x01(\tR\x05maker\x12\x1e\n" +
	"\n" +
	"inputToken\x18\x06 \x01(\tR\n" +
	"inputToken\x12 \n" +
	"\voutputToken\x18\a \x01(\tR\voutputToken\x12\x1a\n" +
	"\bamountIn\x18\b \x01(\tR\bamountIn\x12\"\n" +
	"\fminAmountOut\x18\t \x01(\tR\fminAmountOut\x12(\n" +
	"\x0ftriggerPriceX18\x18\n" +
	" \x01(\tR\x0ftriggerPriceX18\x12\x16\n" +
	"\x06expiry\x18\v \x01(\tR\x06expiry\x12\x14\n" +
	"\x05nonce\x18\f \x01(\tR\x05nonce\x12\x1c\n" +
	"\trecipient\x18\r \x01(\tR\trecipient\x12\x16\n" +
	"\x06source\x18\x0e \x01(\tR\x06source\x12\x16\n" +
	"\x06status\x18\x0f \x01(\tR\x06status\x12\"\n" +
	"\fstatusReason\x18\x10 \x01(\tR\fstatusReason\x12(\n" +
	"\x0fsubmittedTxHash\x18\x11 \x01(\tR\x0fsubmittedTxHash\x12&\n" +
	"\x0eexecutedTxHash\x18\x12 \x01(\tR\x0eexecutedTxHash\x12(\n" +
	"\x0fcancelledTxHash\x18\x13 \x01(\tR\x0fcancelledTxHash\x12*\n" +
	"\x10lastCheckedBlock\x18\x14 \x01(\x03R\x10lastCheckedBlock\x12\x1c\n" +
	"\tcreatedAt\x18\x15 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x16 \x01(\tR\tupdatedAt\x120\n" +
	"\x06notice\x18\x17 \x01(\v2\x18.executor.ResponseNoticeR\x06notice\x122\n" +
	"\x14maxExecutorRewardBps\x18\x18 \x01(\tR\x14maxExecutorRewardBps\x12*\n" +
	"\x10executorFeeToken\x18\x19 \x01(\tR\x10executorFeeToken\x12*\n" +
	"\x10estimatedGasUsed\x18\x1a \x01(\tR\x10estimatedGasUsed\x12(\n" +
	"\x0fgasPriceAtQuote\x18\x1b \x01(\tR\x0fgasPriceAtQuote\x12$\n" +
	"\rrewardQuoteAt\x18\x1c \x01(\tR\rrewardQuoteAt\x12>\n" +
	"\x1alastRequiredExecutorReward\x18\x1d \x01(\tR\x1alastRequiredExecutorReward\x12,\n" +
	"\x11lastRewardCheckAt\x18\x1e \x01(\tR\x11lastRewardCheckAt\x122\n" +
	"\x14lastExecutionCheckAt\x18\x1f \x01(\tR\x14lastExecutionCheckAt\x12(\n" +
	"\x0flastBlockReason\x18  \x01(\tR\x0flastBlockReason\x12*\n" +
	"\x10settledAmountOut\x18! \x01(\tR\x10settledAmountOut\x124\n" +
	"\x15settledExecutorReward\x18\" \x01(\tR\x15settledExecutorReward2\xe8\x01\n" +
	"\bExecutor\x12J\n" +
	"\vCreateOrder\x12\x1c.executor.CreateOrderRequest\x1a\x1d.executor.CreateOrderResponse\x12M\n" +
	"\fCancelOrders\x12\x1d.executor.CancelOrdersRequest\x1a\x1e.executor.CancelOrdersResponse\x12A\n" +
	"\bGetOrder\x12\x19.executor.GetOrderRequest\x1a\x1a.executor.GetOrderResponseB\fZ\n" +
	"./executorb\x06proto3"

var (
	file_proto_executor_proto_rawDescOnce sync.Once
	file_proto_executor_proto_rawDescData []byte
)

func file_proto_executor_proto_rawDescGZIP() []byte {
	file_proto_executor_proto_rawDescOnce.Do(func() {
		file_proto_executor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_executor_proto_rawDesc), len(file_proto_executor_proto_rawDesc)))
	})
	return file_proto_executor_proto_rawDescData
}

var file_proto_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_executor_proto_goTypes = []any{
	(*ResponseNotice)(nil),       // 0: executor.ResponseNotice
	(*CreateOrderRequest)(nil),   // 1: executor.CreateOrderRequest
	(*CreateOrderResponse)(nil),  // 2: executor.CreateOrderResponse
	(*CancelOrderItem)(nil),      // 3: executor.CancelOrderItem
	(*CancelOrdersRequest)(nil),  // 4: executor.CancelOrdersRequest
	(*CancelOrdersResult)(nil),   // 5: executor.CancelOrdersResult
	(*CancelOrdersResponse)(nil), // 6: executor.CancelOrdersResponse
	(*GetOrderRequest)(nil),      // 7: executor.GetOrderRequest
	(*GetOrderResponse)(nil),     // 8: executor.GetOrderResponse
}
var file_proto_executor_proto_depIdxs = []int32{
	8,  // 0: executor.CreateOrderResponse.order:type_name -> executor.GetOrderResponse
	0,  // 1: executor.CreateOrderResponse.notice:type_name -> executor.ResponseNotice
	3,  // 2: executor.CancelOrdersRequest.orders:type_name -> executor.CancelOrderItem
	8,  // 3: executor.CancelOrdersResult.order:type_name -> executor.GetOrderResponse
	5,  // 4: executor.CancelOrdersResponse.results:type_name -> executor.CancelOrdersResult
	0,  // 5: executor.CancelOrdersResponse.notice:type_name -> executor.ResponseNotice
	0,  // 6: executor.GetOrderResponse.notice:type_name -> executor.ResponseNotice
	1,  // 7: executor.Executor.CreateOrder:input_type -> executor.CreateOrderRequest
	4,  // 8: executor.Executor.CancelOrders:input_type -> executor.CancelOrdersRequest
	7,  // 9: executor.Executor.GetOrder:input_type -> executor.GetOrderRequest
	2,  // 10: executor.Executor.CreateOrder:output_type -> executor.CreateOrderResponse
	6,  // 11: executor.Executor.CancelOrders:output_type -> executor.CancelOrdersResponse
	8,  // 12: executor.Executor.GetOrder:output_type -> executor.GetOrderResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_executor_proto_init() }
func file_proto_executor_proto_init() {
	if File_proto_executor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_executor_proto_rawDesc), len(file_proto_executor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_executor_proto_goTypes,
		DependencyIndexes: file_proto_executor_proto_depIdxs,
		MessageInfos:      file_proto_executor_proto_msgTypes,
	}.Build()
	File_proto_executor_proto = out.File
	file_proto_executor_proto_goTypes = nil
	file_proto_executor_proto_depIdxs = nil
}
