// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: executor.proto

package server

import (
	"context"

	"fluxswap-backend/rpc/executor"
	"fluxswap-backend/rpc/internal/logic"
	"fluxswap-backend/rpc/internal/svc"
)

type ExecutorServer struct {
	svcCtx *svc.ServiceContext
	executor.UnimplementedExecutorServer
}

func NewExecutorServer(svcCtx *svc.ServiceContext) *ExecutorServer {
	return &ExecutorServer{
		svcCtx: svcCtx,
	}
}

func (s *ExecutorServer) CreateOrder(ctx context.Context, in *executor.CreateOrderRequest) (*executor.CreateOrderResponse, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

func (s *ExecutorServer) CancelOrders(ctx context.Context, in *executor.CancelOrdersRequest) (*executor.CancelOrdersResponse, error) {
	l := logic.NewCancelOrdersLogic(ctx, s.svcCtx)
	return l.CancelOrders(in)
}

func (s *ExecutorServer) ListOrders(ctx context.Context, in *executor.ListOrdersRequest) (*executor.ListOrdersResponse, error) {
	l := logic.NewListOrdersLogic(ctx, s.svcCtx)
	return l.ListOrders(in)
}

func (s *ExecutorServer) ListOrderUpdates(ctx context.Context, in *executor.ListOrderUpdatesRequest) (*executor.ListOrderUpdatesResponse, error) {
	l := logic.NewListOrderUpdatesLogic(ctx, s.svcCtx)
	return l.ListOrderUpdates(in)
}

func (s *ExecutorServer) GetBestRoute(ctx context.Context, in *executor.GetBestRouteRequest) (*executor.GetBestRouteResponse, error) {
	l := logic.NewGetBestRouteLogic(ctx, s.svcCtx)
	return l.GetBestRoute(in)
}
