// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: executor.proto

package executorclient

import (
	"context"

	"fluxswap-backend/rpc/executor"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CancelOrderItem          = executor.CancelOrderItem
	CancelOrdersRequest      = executor.CancelOrdersRequest
	CancelOrdersResponse     = executor.CancelOrdersResponse
	CancelOrdersResult       = executor.CancelOrdersResult
	CreateOrderRequest       = executor.CreateOrderRequest
	CreateOrderResponse      = executor.CreateOrderResponse
	GetBestRouteRequest      = executor.GetBestRouteRequest
	GetBestRouteResponse     = executor.GetBestRouteResponse
	GetOrderResponse         = executor.GetOrderResponse
	ListOrderUpdatesRequest  = executor.ListOrderUpdatesRequest
	ListOrderUpdatesResponse = executor.ListOrderUpdatesResponse
	ListOrdersRequest        = executor.ListOrdersRequest
	ListOrdersResponse       = executor.ListOrdersResponse
	ResponseNotice           = executor.ResponseNotice
	RouteExecution           = executor.RouteExecution
	RoutePath                = executor.RoutePath
	RouteQuote               = executor.RouteQuote
	RouteView                = executor.RouteView

	Executor interface {
		CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
		CancelOrders(ctx context.Context, in *CancelOrdersRequest, opts ...grpc.CallOption) (*CancelOrdersResponse, error)
		ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error)
		ListOrderUpdates(ctx context.Context, in *ListOrderUpdatesRequest, opts ...grpc.CallOption) (*ListOrderUpdatesResponse, error)
		GetBestRoute(ctx context.Context, in *GetBestRouteRequest, opts ...grpc.CallOption) (*GetBestRouteResponse, error)
	}

	defaultExecutor struct {
		cli zrpc.Client
	}
)

func NewExecutor(cli zrpc.Client) Executor {
	return &defaultExecutor{
		cli: cli,
	}
}

func (m *defaultExecutor) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	client := executor.NewExecutorClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

func (m *defaultExecutor) CancelOrders(ctx context.Context, in *CancelOrdersRequest, opts ...grpc.CallOption) (*CancelOrdersResponse, error) {
	client := executor.NewExecutorClient(m.cli.Conn())
	return client.CancelOrders(ctx, in, opts...)
}

func (m *defaultExecutor) ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error) {
	client := executor.NewExecutorClient(m.cli.Conn())
	return client.ListOrders(ctx, in, opts...)
}

func (m *defaultExecutor) ListOrderUpdates(ctx context.Context, in *ListOrderUpdatesRequest, opts ...grpc.CallOption) (*ListOrderUpdatesResponse, error) {
	client := executor.NewExecutorClient(m.cli.Conn())
	return client.ListOrderUpdates(ctx, in, opts...)
}

func (m *defaultExecutor) GetBestRoute(ctx context.Context, in *GetBestRouteRequest, opts ...grpc.CallOption) (*GetBestRouteResponse, error) {
	client := executor.NewExecutorClient(m.cli.Conn())
	return client.GetBestRoute(ctx, in, opts...)
}
