// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: executor.proto

package executorclient

import (
	"context"

	"fluxswap-backend/rpc/executor"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CancelOrderItem      = executor.CancelOrderItem
	CancelOrdersRequest  = executor.CancelOrdersRequest
	CancelOrdersResponse = executor.CancelOrdersResponse
	CancelOrdersResult   = executor.CancelOrdersResult
	CreateOrderRequest   = executor.CreateOrderRequest
	CreateOrderResponse  = executor.CreateOrderResponse
	GetOrderRequest      = executor.GetOrderRequest
	GetOrderResponse     = executor.GetOrderResponse
	ResponseNotice       = executor.ResponseNotice

	Executor interface {
		CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
		CancelOrders(ctx context.Context, in *CancelOrdersRequest, opts ...grpc.CallOption) (*CancelOrdersResponse, error)
		GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error)
	}

	defaultExecutor struct {
		cli zrpc.Client
	}
)

func NewExecutor(cli zrpc.Client) Executor {
	return &defaultExecutor{
		cli: cli,
	}
}

func (m *defaultExecutor) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	client := executor.NewExecutorClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

func (m *defaultExecutor) CancelOrders(ctx context.Context, in *CancelOrdersRequest, opts ...grpc.CallOption) (*CancelOrdersResponse, error) {
	client := executor.NewExecutorClient(m.cli.Conn())
	return client.CancelOrders(ctx, in, opts...)
}

func (m *defaultExecutor) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	client := executor.NewExecutorClient(m.cli.Conn())
	return client.GetOrder(ctx, in, opts...)
}
