// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: executor.proto

package server

import (
	"context"

	"fluxswap-executor/rpc/executor"
	"fluxswap-executor/rpc/internal/logic"
	"fluxswap-executor/rpc/internal/svc"
)

type ExecutorServer struct {
	svcCtx *svc.ServiceContext
	executor.UnimplementedExecutorServer
}

func NewExecutorServer(svcCtx *svc.ServiceContext) *ExecutorServer {
	return &ExecutorServer{
		svcCtx: svcCtx,
	}
}

func (s *ExecutorServer) Ping(ctx context.Context, in *executor.PingRequest) (*executor.PingResponse, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *ExecutorServer) CreateOrder(ctx context.Context, in *executor.CreateOrderRequest) (*executor.CreateOrderResponse, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

func (s *ExecutorServer) CancelOrders(ctx context.Context, in *executor.CancelOrdersRequest) (*executor.CancelOrdersResponse, error) {
	l := logic.NewCancelOrdersLogic(ctx, s.svcCtx)
	return l.CancelOrders(in)
}

func (s *ExecutorServer) ApplyOrderEvent(ctx context.Context, in *executor.ApplyOrderEventRequest) (*executor.ApplyOrderEventResponse, error) {
	l := logic.NewApplyOrderEventLogic(ctx, s.svcCtx)
	return l.ApplyOrderEvent(in)
}

func (s *ExecutorServer) GetOrder(ctx context.Context, in *executor.GetOrderRequest) (*executor.GetOrderResponse, error) {
	l := logic.NewGetOrderLogic(ctx, s.svcCtx)
	return l.GetOrder(in)
}
